### ISSUE TITLE
show marked question in quiz sheet

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/CBOnlineApp#146]
**Describe the feature you'd like**
Show marked items in the quiz bottom similar to web

**Comment by Zyro9922** [comment]
Can you explain more what how do you want it to be?

**Comment by Zyro9922** [comment]
How do you want it and how does it look on the web? Haven't tried any quiz on CB website

**Comment by aggarwalpulkit596** [comment]
You can try by playing one by enrolling in Android trail course  it does have the quiz in free section you play that you'll know

**Comment by jddeep** [comment]
@aggarwalpulkit596 I would like to work on this issue as a part of BOSS 2019. Can you guide me through what is the issue here? Thanks

**Comment by aggarwalpulkit596** [comment]
Implementation similiar to web
![Screenshot 2019-05-14 at 1 33 30 PM](https://user-images.githubusercontent.com/29139786/57693974-23c06b00-7668-11e9-920f-a2c6855ab140.png)

**Comment by aggarwalpulkit596** [comment]
The current implementation  of the bottom sheet doesn't show any marked/correct/incorrect quiz response in the bottom sheet

**Comment by jddeep** [comment]
Okay I will look into that.

**Comment by raystatic** [comment]
if it is still open I would like to work on it

**Comment by aggarwalpulkit596** [comment]
@raystatic sure go ahead

**Comment by ShivanshRakesh** [comment]
Is it still open? If yes, I would like to work on this issue.

**Comment by HardikSo** [comment]
is it still open?

**Comment by adityastic** [comment]
@aggarwalpulkit596 Its been more than 2 week to this issue, can I take this up?

**Comment by aggarwalpulkit596** [comment]
Yup go ahead
