### ISSUE TITLE
Show leaderboard in Course Consumption Page

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/CBOnlineApp#151]
**Describe the feature you'd like**
Show leaderboard in the course consumption page

**Comment by imashwani** [comment]
Can i take up the issue @aggarwalpulkit596 ?

**Comment by shubhamofbce** [comment]
I also want to work on this issue

**Comment by shubhamofbce** [comment]
Where is that course consumption page??

**Comment by shubhamofbce** [comment]
You want leaderboard on the overview page as it is on the website and is leaderboard only available for premium courses????

**Comment by aggarwalpulkit596** [comment]
yes exactly like the website and there is already leaderboard adapter you just have to show them
and the leaderboard is not for every course try enrolling to a different course c++ course have a leaderboard i guess

**Comment by radharaniraj** [comment]
i would also like to work on this issue,if it is still open

**Comment by aggarwalpulkit596** [comment]
@radharaniraj Yeah Go Ahead
