### ISSUE TITLE
Add Tags Section to Course Activity

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/CBOnlineApp#152]
For reference see image below
![Screenshot 2019-05-14 at 1 20 39 PM](https://user-images.githubusercontent.com/29139786/57680484-5b6cea00-764b-11e9-8fba-a206d6c798f6.png)

**Comment by raystatic** [comment]
how will i get the topic names for a particular course and currently there is a section called "What will you learn" in this activity.. is it similar to that?

**Comment by aggarwalpulkit596** [comment]
Yes it is the same activity and there is already a class tags which is populated in the v2/course-id end point you just have to inflate them using a chip group

**Comment by shubhamofbce** [comment]
![ss for app](https://user-images.githubusercontent.com/45156638/57972868-b1c88880-79bd-11e9-9911-da8541bd693b.jpeg)
