### ISSUE TITLE
Create Quiz Result Screen

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/CBOnlineApp#153]
References
![Screenshot 2019-05-14 at 1 33 41 PM](https://user-images.githubusercontent.com/29139786/57681231-ebf7fa00-764c-11e9-81e0-474f2e568c75.png)

**Comment by anujji1999** [comment]
@aggarwalpulkit596 can you please explain the issue?
Do we have to create this screen?
Or is there any problem with the screen?

**Comment by aggarwalpulkit596** [comment]
Create this screen in the Android app

**Comment by thedevelopersanjeev** [comment]
I would like to work on this issue @aggarwalpulkit596

**Comment by thedevelopersanjeev** [comment]
This is the layout that I have created...
![cbquizresult](https://user-images.githubusercontent.com/34043056/57738505-6bc5a900-76cd-11e9-8931-03e47c75e40c.jpg)
Please review @aggarwalpulkit596 
Suggestions are welcome : )

**Comment by aggarwalpulkit596** [comment]
LGTM

**Comment by thedevelopersanjeev** [comment]
PR Created @aggarwalpulkit596
