### ISSUE TITLE
Dropdown in Course section not working

### ISSUE THREAD

**Issue by luckyman20** [coding-blocks/CBOnlineApp#154]
**Describe the bug**
When you see any course and go to its `What will you learn` section, there are cards representing each section of the course. When you click on the card, it will expand but when you click on the dropdown button, nothing happens.

There are solutions I can think of - remove the dropdown button or make it workable.

**To Reproduce**
Home -> Go to any Course -> `What will you learn` section -> Try clicking dropdown button

**Expected behavior**
The dropdown button should have worked.

**Smartphone Info:**
Device - Pixel 2 XL
Android Version - Android Q Beta

**Would you like to work on the issue?**
- [x] Yes

**Comment by aggarwalpulkit596** [comment]
It isn't drop-down it is a list and and you can a progressloader or a shimmer layout there
