### ISSUE TITLE
Refactor: Text is Hard-coded

### ISSUE THREAD

**Issue by luckyman20** [coding-blocks/CBOnlineApp#155]
**Describe the feature you'd like**
Currently, in many XML files, the text is hard-coded while it should be placed in `strings.xml` file.

**Additional context**
If placed in `strings.xml` then we can introduce the Hindi language too.

**Would you like to work on the issue?**
- [x] Yes

**Comment by SaumyaSingh1** [comment]
Please add the bounty for this issue .

**Comment by aggarwalpulkit596** [comment]
i will add the bounty depending upon the work done in the PR
