### ISSUE TITLE
Login Activity layout error in landscape mode

### ISSUE THREAD

**Issue by codedsun** [coding-blocks/CBOnlineApp#156]
**Describe the bug**

The login activity has layout currently for portrait and it's not properly visible in landscape mode

**To Reproduce**
Open the app

**Expected behavior**
The activity should be portrait or a new layout for landscape should be made.

**Logs**
None

**Screenshots**
![screenshot-1557833704284](https://user-images.githubusercontent.com/20026440/57694865-77cc4f00-766a-11e9-8df0-b61e5132e9e5.jpg)

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by aggarwalpulkit596** [comment]
Make a seperate layout for landscape
