### ISSUE TITLE
Refactor the whole code

### ISSUE THREAD

**Issue by codedsun** [coding-blocks/CBOnlineApp#157]
**Describe the bug**
The app is currently not following standards of dimens, string, colors and constants. Need to refactor it according to the standards.

**Expected behavior**
It should be following it.

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by aggarwalpulkit596** [comment]
You can't refractor the entire project in one go and neither i can check it try 
You can start by doing one activity/fragment at a time

**Comment by codedsun** [comment]
@aggarwalpulkit596 I just initiated an issue here, just to refer every time a PR is submitted regarding the same.

**Comment by codedsun** [comment]
@aggarwalpulkit596 I see in layout files, we have used snackcase and for some we have used camelcase, what should be the best to go with?

**Comment by aggarwalpulkit596** [comment]
camelCase 🙂
