### ISSUE TITLE
Issues in Contact Us

### ISSUE THREAD

**Issue by codedsun** [coding-blocks/CBOnlineApp#163]
**Describe the bug**
Contact US On Navigation Drawer has following error
1. Toolbar Back press not working
2. Toolbar name is wrong
3. Toll free number is not cliclacble
4. Address has for some text issues, where characters cant be displayed
5. I think it needs update for all the centres of CB

**To Reproduce**
1. Go to Contact us from nav drawer

**Expected behavior**
The above should not be their

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by codedsun** [comment]
@aggarwalpulkit596 How is the bounty calculated? and what shall be the layout for displaying all the center info?

**Comment by aggarwalpulkit596** [comment]
It usually depends upon the complexity of work and keep the layout simple just make a scrollview and add all of the details just the way it is currently shown for a single center

**Comment by mannprerak2** [comment]
i would like to work on this too

**Comment by mannprerak2** [comment]
please review my PR, #165 

And I think for showing all the centers we should instead use a button to open the CB website
because details may become stale as its currently hardcoded
This should be done in a different PR as complete remodeling of the AboutActivity UI is required

**Comment by aggarwalpulkit596** [comment]
These details do not change office address, number are not going to change for a long time period and it's hardcoded in the website itself and just make 3 copies of the current layout and add the information from website

**Comment by mannprerak2** [comment]
okay sure

**Comment by codedsun** [comment]
@aggarwalpulkit596 Is this allowed that someone else can take the work widout even asking? And that too the PR gets merged.
I was working on this and was to send a PR.

**Comment by aggarwalpulkit596** [comment]
@codedsun no actually this is my mistake will make sure this will not happen in future .
Don't worry I'll make it upto you in you next PR

**Comment by mannprerak2** [comment]
@codedsun I am really sorry about this, I did notice most of these bugs and saw your issue before i could file mine.
I'll be sure to ask firsthand next time before starting to work
But i think sometimes clashes are bound to happen

**Comment by codedsun** [comment]
@aggarwalpulkit596 Can i claim bounty for opening the issue?
