### ISSUE TITLE
Add free label to free section of trial course in My Course Activity

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/CBOnlineApp#164]

**Comment by luckyman20** [comment]
@aggarwalpulkit596 I would like to work on this issue :)

**Comment by aggarwalpulkit596** [comment]
Go ahead

**Comment by shubhamofbce** [comment]
I would like to solve this issue

**Comment by SaumyaSingh1** [comment]
But free label is already marked here.

![image](https://user-images.githubusercontent.com/46818757/57966771-07784300-7974-11e9-8979-6ac47b141fee.png)

Am I right ? Please guide .

**Comment by aggarwalpulkit596** [comment]
Add it to course individual sections

**Comment by luckyman20** [comment]
@SaumyaSingh1 You have to mark the sections of course content that are free, I guess.

Also, sorry, I won't be able to work on this issue anymore.

**Comment by SaumyaSingh1** [comment]
Free label in few sections , is it something like this ...
![image](https://user-images.githubusercontent.com/46818757/57966855-5377b780-7975-11e9-922a-8a42116db81b.png)

**Comment by aggarwalpulkit596** [comment]
Yes exactly like this

**Comment by SaumyaSingh1** [comment]
so, upto how many sections should we mark free label ? And are we supposed to do this in all the courses ?

**Comment by aggarwalpulkit596** [comment]
For all the sections which are not premium and obviously yes for all the courses

**Comment by SaumyaSingh1** [comment]
okay :)

**Comment by SaumyaSingh1** [comment]
@aggarwalpulkit596 I have added the free label . looks like this ..
![image](https://user-images.githubusercontent.com/46818757/57968051-20d4bb80-7983-11e9-8638-eb1d1a03d3aa.png)

But right now the label is for all sections . Need sometime to make it confined to the sections which are not premium :)

**Comment by aggarwalpulkit596** [comment]
Does it good to you ? I don't think so make design similar to website

**Comment by SaumyaSingh1** [comment]
Okay i will make design similar to the website .

**Comment by shubhamofbce** [comment]
@aggarwalpulkit596 From where can we know that which courses are free and which are not??

**Comment by shubhamofbce** [comment]
![gradient in cb free](https://user-images.githubusercontent.com/45156638/57970290-2a6b1d00-799d-11e9-9dcf-39646a139703.jpeg)
I am also at this stage and now i just want to know that from where i can get the data that which courses are free and which are not????

**Comment by shubhamofbce** [comment]
I did it.
Is it alright or @aggarwalpulkit596 you need more modificitaions??
Its working fine for all the courses.

![free working everywhere](https://user-images.githubusercontent.com/45156638/57971150-cef25c80-79a7-11e9-848d-769238e345d4.jpeg)

**Comment by shubhamofbce** [comment]
Its all set now looking exactly like the website can i send a pr now??? @aggarwalpulkit596 

![all set now](https://user-images.githubusercontent.com/45156638/57971479-6f4a8000-79ac-11e9-9a88-96422e306a0b.jpeg)

**Comment by aggarwalpulkit596** [comment]
If @SaumyaSingh1 is okay with this you can send a PR @shubhamofbce

**Comment by shubhamofbce** [comment]
@aggarwalpulkit596 please review

**Comment by aggarwalpulkit596** [comment]
@shubhamofbce i told you @SaumyaSingh1 asked it first if she doesn't make a pr by tomorrow I'll your pr

**Comment by shubhamofbce** [comment]
But i asked to work on this first , You can see the comments from the begining. I asked two days ago she commented today.

**Comment by aggarwalpulkit596** [comment]
@SaumyaSingh1 i guess it's okay then

**Comment by shubhamofbce** [comment]
Thank you @aggarwalpulkit596 How can i claim my bounty

**Comment by SaumyaSingh1** [comment]
@aggarwalpulkit596 Because of my exams i was not able to complete the task . But I have done half of the work .
Issue is still open ! are we still supposed to resolve same problem.
Thanks for the guidance @aggarwalpulkit596

**Comment by aggarwalpulkit596** [comment]
@SaumyaSingh1 yeah you can still work on this follow the design which @shubhamofbce used but his method was incorrect so i had to revert that

**Comment by SaumyaSingh1** [comment]
Okay

**Comment by SaumyaSingh1** [comment]
#195

**Comment by shubhamofbce** [comment]
Did @SaumyaSingh1 resolved the issue or is it still open??? @aggarwalpulkit596

**Comment by aggarwalpulkit596** [comment]
It is still open

**Comment by shubhamofbce** [comment]
@aggarwalpulkit596 I made a pr with proper logic this time do check it.

**Comment by shubhamofbce** [comment]
@aggarwalpulkit596 #209 has no conflicts and got all tests passed too. please review for one last time.
