### ISSUE TITLE
Add databinding to activities.

### ISSUE THREAD

**Issue by jddeep** [coding-blocks/CBOnlineApp#170]
With the databinding library of android the boilerplate code could be reduced alot.

[ ]  Add databinding to activities
[ ]  Add databinding to adapters
[ ]  Add databinding to fragments

**Would you like to work on issue**
Yes

**Comment by jddeep** [comment]
@aggarwalpulkit596 Please add bounty labels to this.

**Comment by aggarwalpulkit596** [comment]
@jddeep start with recycler view adapter first

**Comment by adityastic** [comment]
@jddeep If you're not working on this, can I take this up?

**Comment by adityastic** [comment]
@aggarwalpulkit596 assign bounty here

**Comment by aggarwalpulkit596** [comment]
@adityastic it will be done in seperate PR's so i will assign points accordingly depending upon the amount of work done in every PR

**Comment by adityastic** [comment]
@aggarwalpulkit596 got it. I'll start from morning itself

**Comment by adityastic** [comment]
@aggarwalpulkit596 https://github.com/fossasia/badge-magic-android/pull/419
