### ISSUE TITLE
Display a warning dialog before ending the quiz attempt screen.

### ISSUE THREAD

**Issue by thedevelopersanjeev** [coding-blocks/CBOnlineApp#175]
**Describe the feature you'd like**
There is no warning displayed when we end the quiz while attempting. There should be warning like `You have not submitted the quiz, your score will not be updated` 
and add submit/cancel button on the warning dialog.

**Comment by thedevelopersanjeev** [comment]
Can I start working on this issue @aggarwalpulkit596

**Comment by aggarwalpulkit596** [comment]
See #181
