### ISSUE TITLE
Implement ViewModels for Course and Video Activities

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/CBOnlineApp#178]
**Describe the feature you'd like**
Implement View Models for Course And Video Activities with koin

**Comment by adityastic** [comment]
I would like to work on this issue

**Comment by sahilbhosale63** [comment]
I would like to work on this issue.

**Comment by aggarwalpulkit596** [comment]
Ask @adityastic first if he's okay with it you can start working

**Comment by adityastic** [comment]
@aggarwalpulkit596 I'll be working on it

**Comment by adityastic** [comment]
@aggarwalpulkit596 there are a total of 8 activities left which do not follow the MVVM architecture, will you open specific issues for specific activity and assign a bounty to it?

**Comment by aggarwalpulkit596** [comment]
@adityastic probably not because they are quite simple and don't require anything much to refractor I'll be probably doing it on my own

**Comment by adityastic** [comment]
@aggarwalpulkit596 if you wish, I can do all the files with this issue, you can give me a small amount of extra bounty for it.
