### ISSUE TITLE
Implement Dynamic App Shortcut

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/CBOnlineApp#179]
**Describe the feature you'd like**
Implement Dynamic App Shortcut for course with maximum usage similar to like WhatsApp implementation

References
https://developer.android.com/guide/topics/ui/shortcuts

**Comment by rkishan516** [comment]
I would like to work on this.

**Comment by aggarwalpulkit596** [comment]
@rkishan516 Go Ahead

**Comment by raystatic** [comment]
if this is still open i would like to work on it

**Comment by rkishan516** [comment]
Sorry, but I am working on this.

**Comment by raystatic** [comment]
okay

**Comment by rkishan516** [comment]
@aggarwalpulkit596 For using API we need minimum API 25 but current is 21.

**Comment by aggarwalpulkit596** [comment]
Obviously not if i want to implement a specific feature restricted to API>27 should i update min sdk to api 27 ? I don't thinks so

**Comment by rkishan516** [comment]
Yup, got it.

**Comment by rkishan516** [comment]
@aggarwalpulkit596 
This code is creating crash

var addShortcut = findViewById<Button>(R.id.addShortcut)
val clickListener = View.OnClickListener {view ->

            when (view.getId()) {
                R.id.addShortcut -> createShortcut(this,
                    HomeActivity::class.java,
                    courseName,
                    R.mipmap.ic_launcher)
            }
}
addShortcut.setOnClickListener(clickListener)

**Comment by aggarwalpulkit596** [comment]
This is not how it will be implemented please android docs

**Comment by adityastic** [comment]
@aggarwalpulkit596 If I am correct, are you the same guy who contributes for fossasia as well?

**Comment by aggarwalpulkit596** [comment]
Yes @adityastic

**Comment by adityastic** [comment]
@aggarwalpulkit596 great, happy to find someone from the same community

**Comment by rkishan516** [comment]
@aggarwalpulkit596 
Can you please suggest me how I can change HomeActivity::class.java with that CourseActivity
createShortcut(this@CourseActivity,HomeActivity::class.java, this.courseName, R.mipmap.ic_launcher)

**Comment by aggarwalpulkit596** [comment]
See Implementation of MyCourse Dynamic Shortcut

**Comment by rkishan516** [comment]
@aggarwalpulkit596 
Actually there is nothing like dynamic Shortcut. That is just for Showing HomeActivity only.

**Comment by aggarwalpulkit596** [comment]
No there is a dynamic shortcut which open my courses only if the user is logged in

**Comment by rkishan516** [comment]
That code is this I think
@TargetApi(25)
    private fun createShortcut() {
        val sM = getSystemService(ShortcutManager::class.java)
        val intent1 = Intent(applicationContext, HomeActivity::class.java)
        intent1.action = Intent.ACTION_VIEW
        val shortcut1 = ShortcutInfo.Builder(this, "shortcut1")
            .setIntent(intent1)
            .setLongLabel("My Tickets")
            .setShortLabel("Open to show all tickets")
            .setDisabledMessage("Login to open this")
            .setIcon(Icon.createWithResource(this, R.mipmap.ic_launcher))
            .build()
        sM.dynamicShortcuts = Arrays.asList(shortcut1)
    }

    @TargetApi(25)
    private fun removeShortcuts() {
        val shortcutManager = getSystemService(ShortcutManager::class.java)
        shortcutManager.disableShortcuts(Arrays.asList("shortcut1"))
        shortcutManager.removeAllDynamicShortcuts()
    }

**Comment by aggarwalpulkit596** [comment]
Yes exactly this is the one

**Comment by rkishan516** [comment]
but this is to open HomeActivity
val intent1 = Intent(applicationContext, HomeActivity::class.java)

**Comment by aggarwalpulkit596** [comment]
Similarly any other activity can be opened

**Comment by rkishan516** [comment]
but when I tried to Open CourseActivity by this then the shortcut is showing toast of "App isn't install"

**Comment by aggarwalpulkit596** [comment]
You might be missing something this because this is the way to open dynamic shortcut

**Comment by rkishan516** [comment]
actually my way is :
    createShortcut(this@CourseActivity,this@CourseActivity::class.java, this.courseName, R.mipmap.ic_launcher)

where createShortcut is : 

fun createShortcut(activity: Activity, activityToOpen: Class<*>, title: String, @DrawableRes icon: Int) {
    val shortcutIntent = Intent(activity, activityToOpen)
    shortcutIntent.action = Intent.ACTION_VIEW
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) {
        // code for adding shortcut on pre oreo device
        val intent = Intent("com.android.launcher.action.INSTALL_SHORTCUT")
        intent.putExtra(Intent.EXTRA_SHORTCUT_INTENT, shortcutIntent)
        intent.putExtra(Intent.EXTRA_SHORTCUT_NAME, title)
        intent.putExtra("duplicate", false)
        val parcelable = Intent.ShortcutIconResource.fromContext(activity, icon)
        intent.putExtra(Intent.EXTRA_SHORTCUT_ICON_RESOURCE, parcelable)
        activity.sendBroadcast(intent)
        println("added_to_homescreen")
    } else {
        val shortcutManager = activity.getSystemService(ShortcutManager::class.java)!!
        if (shortcutManager.isRequestPinShortcutSupported) {
            val pinShortcutInfo = ShortcutInfo.Builder(activity, "browser-shortcut-")
                .setIntent(shortcutIntent)
                .setIcon(Icon.createWithResource(activity, icon))
                .setShortLabel(title)
                .build()

            shortcutManager.requestPinShortcut(pinShortcutInfo, null)
            println("added_to_homescreen")
        } else {
            println("failed_to_add")
        }
    }
}

**Comment by aggarwalpulkit596** [comment]
It is probably happening of debug apk package name works fine for signed apk

**Comment by rkishan516** [comment]
but for opening a CourseActivity there should be one id given in code.
given by me above.

**Comment by rkishan516** [comment]
> It is probably happening of debug apk package name works fine for signed apk

So, what I do ?

**Comment by aggarwalpulkit596** [comment]
First of all this is not way it will work And Secondly you have to Open My course Activity with course having having maximum hits accessed from course run dao

**Comment by aggarwalpulkit596** [comment]
> > It is probably happening of debug apk package name works fine for signed apk
> 
> So, what I do ?

Remove applicationId tag in build.gradle

**Comment by rkishan516** [comment]
Okay. I will.

**Comment by rkishan516** [comment]
> First of all this is not way it will work And Secondly you have to Open My course Activity with course having having maximum hits accessed from course run dao

Not Getting. Why we will add My course Activtiy when adding shortcut of any course.

**Comment by aggarwalpulkit596** [comment]
What's the benefit of opening the course activity in the first place ? It's just a page  to enroll into a course MyCourseActitvity is course consumption page

**Comment by rkishan516** [comment]
Ok, got it.

**Comment by rkishan516** [comment]
![Screenshot_20190523-095245](https://user-images.githubusercontent.com/34465683/58225703-fb5bff00-7d40-11e9-8a88-9153b486c6e6.jpeg)
This is my way. is it what your requirement ?

**Comment by aggarwalpulkit596** [comment]
No, make a implementation similiar to of whatsapp which makes top chats dynamic shortcut automatically

**Comment by rkishan516** [comment]
> No, make a implementation similiar to of whatsapp which makes top chats dynamic shortcut automatically

Not getting. Can you give me example.

**Comment by aggarwalpulkit596** [comment]
Check Whatsapp Dynamic App Shortcut you'll know

**Comment by rkishan516** [comment]
where ?

**Comment by aggarwalpulkit596** [comment]
See this https://images.app.goo.gl/BMHajS12oS7ipHpCA

**Comment by rkishan516** [comment]
okay.

**Comment by raystatic** [comment]
if this is open then i would like to work on this

**Comment by rkishan516** [comment]
@raystatic you may because it's taking time for me.

**Comment by HardikSo** [comment]
i would like to work on this.

**Comment by raystatic** [comment]
I am already working on this
