### ISSUE TITLE
Fix MyCourses Swipe to Refresh

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/CBOnlineApp#180]
**Describe the feature you'd like**
Swipe to Refresh in My Courses Fragment keeps on loading data

**Comment by ShridharGoel** [comment]
I would like to work on this.

**Comment by shubhamofbce** [comment]
I can't understand the issue properly In my phone when i swipe to refresh the app loads the data within few seconds

**Comment by aggarwalpulkit596** [comment]
Closing via 0ada1b618ef971be0ce49dc223a9bb9dde15ad6c
