### ISSUE TITLE
Improvise Quiz Activty

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/CBOnlineApp#181]
**Describe the feature you'd like**
There are multiple issues in the quiz so I'll be breaking into separate PR's

- [x] Inappropriate flow of quiz - quiz has an inappropriate flow it should follow a proper flow with proper confirmation at every point

- [x] Incorrect Shimmer Layout for Quiz

- [x] Improve Previous Attempts leaderboard

- [ ] Improve Quiz Layout

- [x] Incorrect Time in Quiz Attempt

- [x] Add Submit Quiz Button in Bottom Sheet

**Comment by thedevelopersanjeev** [comment]
I would like to work on this issue.

**Comment by thedevelopersanjeev** [comment]
Should I create separate PR for each part or all will be done in a single PR? @aggarwalpulkit596

**Comment by aggarwalpulkit596** [comment]
Seperate PR would be fine

**Comment by thedevelopersanjeev** [comment]
For the first part, at what point do we need to show confirmation and should it be in dialog or anything else?
@aggarwalpulkit596

**Comment by aggarwalpulkit596** [comment]
First of all handle back stack correctly then fix the animation currently right to left transition are shown it should be left to right after that don't need to show result card for a submitted quiz

**Comment by aggarwalpulkit596** [comment]
@thedevelopersanjeev and there are few more bugs like go back button is not working in result screen and onBackPress remove the quiz activity instead it should take back to quiz attempt fragment and submit quiz button should not in bottom sheet for already submitted quiz
If you complete all of this I'll give you 500 points

**Comment by thedevelopersanjeev** [comment]
cool. I am working on it.

**Comment by thedevelopersanjeev** [comment]
Can you explain a little bit more about what is wrong in shimmer layout @aggarwalpulkit596 
(Share screenshot if possible)

**Comment by aggarwalpulkit596** [comment]
Currently, Course Activity Shimmer is being used make a separate shimmer for that

**Comment by thedevelopersanjeev** [comment]
How can we improve the quiz layout? @aggarwalpulkit596 
Do you have any other design/idea for it?

**Comment by thedevelopersanjeev** [comment]
@aggarwalpulkit596 please help me in the last part of this issue.

**Comment by adityastic** [comment]
@aggarwalpulkit596 what part is left in this? I would to take that if you agree

**Comment by adityastic** [comment]
@aggarwalpulkit596 what improvements are you looking for in Quiz Layout?
