### ISSUE TITLE
arrow should revert when the list expands in course activity

### ISSUE THREAD

**Issue by raystatic** [coding-blocks/CBOnlineApp#196]
**Describe the bug**
If the list is expanded in course activity, the position of arrow does not change
**To Reproduce**
1. Go to 'course activity'
2. Click on 'one of the item of what will you learn'
3. If the list is expanded, the direction of arrow does not revert

**Expected behavior**
If the list is expanded, the direction of arrow should revert

**Screenshots**
![WhatsApp Image 2019-05-20 at 23 06 03](https://user-images.githubusercontent.com/31301266/58041003-9cd22d80-7b54-11e9-8f71-fa711ccef308.jpeg)

**Smartphone Info:**
|               | |
|---------------|-|
|Device         |<Lenovo k8 note|
|Android Version|Oreo 8.0    |

**Would you like to work on the issue?**
- [x] Yes
- [ ] No
- Other:

**Comment by aggarwalpulkit596** [comment]
Make it implementation similar to course consumption section that is the animation of closing and opening I'll allocate 150 + 100 more if added a progress loader while items are loaded in this adapter

**Comment by raystatic** [comment]
okay
