### ISSUE TITLE
No intent is set for viewpager in the homefragment.

### ISSUE THREAD

**Issue by SaumyaSingh1** [coding-blocks/CBOnlineApp#198]
**Describe the bug**

On clicking the viewpager view  nothing happens.

**To Reproduce**
1. Go to 'Homefragment'
2. Click on 'viewpager that swipes on definite interval'
3. Bug  -> No response on click .

**Expected behavior**
 On clicking the viewpager a new page should open up. 
1. For the first three slides respective course activity should open up.
2. For the 'Share success story ' , the coding block website should open up.

**Would you like to work on the issue?**
- [✔ ] Yes
- [ ] No
- Other:

**Comment by aggarwalpulkit596** [comment]
It's working just fine and it uses routing for this your current implementation work work ever.
