### ISSUE TITLE
Add Download Limit in Settings

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/CBOnlineApp#217]
Add A Limit in Settings to for downloading videos preferably a slider with a minimum of 1GB max Up to 10GB

**Comment by shubhamofbce** [comment]
i would like to work on this issue

**Comment by adityastic** [comment]
@shubhamofbce and this as well?

**Comment by shubhamofbce** [comment]
Yes i m kalam working on this @adityastic i will tell you for sure if i m unable to make this as i m a newbie .

**Comment by adityastic** [comment]
@shubhamofbce we all are newbies brother, let us know if you need any help with this. Kudos

**Comment by shubhamofbce** [comment]
Thanks @adityastic .I will let you know for sure and That statement matters a lot

**Comment by shubhamofbce** [comment]
@aggarwalpulkit596 can you please tell me what action to perform if the download limit is reached??
whether to disconnect the network or pause the doenload or something else??
![download limit](https://user-images.githubusercontent.com/45156638/58631255-9d5e8700-82ff-11e9-862a-1d3837397c27.jpeg)

**Comment by aggarwalpulkit596** [comment]
When a limit is reached ask the user to delete previously downloaded videos delete the video with the oldest date

**Comment by HardikSo** [comment]
is this issue still open?

**Comment by adityastic** [comment]
@shubhamofbce how's the progress bro?

**Comment by adityastic** [comment]
@shubhamofbce any updates on this bro?

**Comment by shubhamofbce** [comment]
@adityastic take this one too. I am busy doing something else. Sorry

**Comment by adityastic** [comment]
@shubhamofbce ok bro. Thanks :)

**Comment by adityastic** [comment]
@aggarwalpulkit596 Alright, so how would I calculate the size of the download beforehand?. There is no way yet to calculate size before the file is downloaded

**Comment by aggarwalpulkit596** [comment]
yup there isn't any way to get size beforehand
so we can do it like
if the threshold is 5GB and the user has used 4.5GB so give it a warning to user with the option to delete the oldest file downloaded or cancel current download and usually videos are roughly > 200mb so we can check approx within a limit not the approx size of download but I can ask videocipher team maybe there is a API for that but for now follow this implementation

**Comment by adityastic** [comment]
Got it
