### ISSUE TITLE
Fix Spotless Kotlin

### ISSUE THREAD

**Issue by adityastic** [coding-blocks/CBOnlineApp#227]
**Describe the feature you'd like**
currently spotless is not working, I can see wildcard imports and useless imports everywhere. Even the code is not indented properly.

**Would you like to work on the issue?**
- [x] Yes
- [ ] No
- Other:

**Comment by adityastic** [comment]
@aggarwalpulkit596 suggestions?

**Comment by adityastic** [comment]
wrong repo.. my bad

**Comment by adityastic** [comment]
@aggarwalpulkit596 this was a tedious and time consuming task, please assign it some bounty if you can :)

**Comment by aggarwalpulkit596** [comment]
Only fix spotless in this pr

**Comment by adityastic** [comment]
@aggarwalpulkit596 got it. Let me update the pr
