### ISSUE TITLE
Find an issue / suggest an improvement

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/CBOnlineApp#234]
Win 20 bounty points by doing either -

* **Find a bug**
For this, you have to mention expected result, and the actual outcome, and post screenshots (if required) to substantiate. Vague bug reports that can't be reproduced will not be entertained

or

* **Suggest a feature**
Suggest a feature that can be added. Flesh it out with technical details, and steps required to implement. Post mocks (if required) to explain the feature. It will be considered for the bounty if the maintainers consider the feature suggestion valid and decide to work on it.

**Comment by adityastic** [comment]
Hey, Evening. I would like to suggest some bugs as well as features:
- Bugs:
    - Fixing Memory Leaks : Memory leaks are particularly serious issues for programs.
        Points:
        1. monitoring leaks over android monitor
        2. fixing leaks respectively
    - Fixing Morphing Issues in Layouts : 
![cb2](https://user-images.githubusercontent.com/11988517/58626905-844fd900-82f3-11e9-9305-659dc6c6fede.jpg)
![cb1](https://user-images.githubusercontent.com/11988517/58626907-85810600-82f3-11e9-9e62-62b908fbb940.jpg)

- Features:
    - Changing the Interface design to use BottomBars : The Current Interface of the app is somewhat outdated. Let's rebase it to the Latest Material Design 
        Points:
        1. This would require use to create the base activity again
        2. Every Layout Change will be confirmed with you before moving forward with it 

    - Theme Support : Lets Provide Users with options to choose the app theme according to the battery level, time of day or choice.
        Points:
        1. This will be available in the settings and users pick the preferred options using a spinner or anything more interactive

    - Allow Users to Rate Courses : This should be available once the user is enrolled in the course, or if he/she has opted for free trial. We have talked about this couple of days back

**Comment by aggarwalpulkit596** [comment]
You can add theme support  and user to rate course it was already on the roadmap but for now skip the complete redesign as that part is already in the process will create an issue myself when the designs are ready

**Comment by adityastic** [comment]
> You can add theme support and allow enrolled user to rate course it was already on the roadmap but for now, skip the complete redesign as that part is already in the process will create an issue myself when the designs are ready

Great.

**Comment by adityastic** [comment]
@aggarwalpulkit596 what about the memory leaks, should I start looking for them? as there is no generic solution for memory leaks, I would have to spend a lot of time to find the ways to fix them. This would be fun to learn as well as well as beneficial for the app as well.

**Comment by aggarwalpulkit596** [comment]
@adityastic instead of finding and fixing new issues you should try already opened up issues as they are on a higher priority

**Comment by adityastic** [comment]
> @adityastic instead of finding and fixing new issues you should try already opened up issues as they are on a higher priority

got it

**Comment by SaumyaSingh1** [comment]
Feature :
Right now in the coding block app we don't have **Get Hired** feature.

Description:
We can have Get Hired feature as on website in our app also . That can be implemented in the Navigation Drawer . 

Screenshot for the idea -

![image](https://user-images.githubusercontent.com/46818757/58960237-663b1a80-87c4-11e9-83d9-752453b446d0.png)

On clicking the same , we can show something as is on web ! Like-

![image](https://user-images.githubusercontent.com/46818757/58960400-c0d47680-87c4-11e9-8b17-11905400b24a.png)

![image](https://user-images.githubusercontent.com/46818757/58960430-cb8f0b80-87c4-11e9-8121-8ed483b3cc80.png)


We can obviously make the UI  very cool  :) 

If you liked the idea , then i will work on it .

**Comment by aggarwalpulkit596** [comment]
@SaumyaSingh1 nice thought but this feature is already in process but yeah you can improvise the layout when I'm done with the basic implementation

**Comment by SaumyaSingh1** [comment]
Sure , I will work on improvising layout :)

Will i get bounty for suggesting this feature? Should I claim for it? @aggarwalpulkit596

**Comment by aggarwalpulkit596** [comment]
Unfortunately not 😅 you can't claim as this feature is already implemented but you can bugs there are a lot of them even a minor UI bug

**Comment by SaumyaSingh1** [comment]
Bug: In the LeaderBoard section , the text "Leaderboard not available ...." is not correctly aligned and so complete text is not readable .

Description : 
The textview can be kept inside scrollview or layout gravity can be changed to center . 


Screenshots:
 
![image](https://user-images.githubusercontent.com/46818757/58970610-64c71d80-87d7-11e9-88de-cabe00c3548e.png)

The page is not even scollable :/


![image](https://user-images.githubusercontent.com/46818757/58970660-790b1a80-87d7-11e9-92f3-671160d8ba76.png)

**Comment by SaumyaSingh1** [comment]
Bug :

In AboutQuizFragment  (trial version) , the Previous attempt draft created doesn't follow any particular ascending or descending order for the time when  created. New/Latest draft should be at top of recyclerview.

Screenshort -
![image](https://user-images.githubusercontent.com/46818757/59146770-d4bfe880-8a0f-11e9-9a59-5dd82777afb5.png)

**Comment by SaumyaSingh1** [comment]
Bug -

For a course i am using trial and paid both the versions .

![image](https://user-images.githubusercontent.com/46818757/59146883-49475700-8a11-11e9-88fb-b5567241b0f7.png)


In both the versions , Free Tag for premium courses is available . If the user is using the paid course then entire course is free , no use of Free Tag on few of the sections .

TRIAL VERSION ✔
![image](https://user-images.githubusercontent.com/46818757/59146944-41d47d80-8a12-11e9-8248-0d4a56f1dce8.png)



PAID COURSE (FREE TAG FOR FEW SECTION ,NOT NEEDED ❌)
![image](https://user-images.githubusercontent.com/46818757/59146980-d63ee000-8a12-11e9-9fdc-ac3648ab56ff.png)

**Comment by championswimmer** [comment]
@SaumyaSingh1 	can you report this is a new issue ?

**Comment by SaumyaSingh1** [comment]
@championswimmer Yes Sure.

**Comment by anujji1999** [comment]
UI Bug -Card Layout in each activity is not properly designed.
Basically, all the cards are not scalable, contents gets overlapped.
![1](https://user-images.githubusercontent.com/33349650/60245147-96fd0400-98d9-11e9-8b7a-0eef57e8e297.jpeg)
![2](https://user-images.githubusercontent.com/33349650/60245164-a2502f80-98d9-11e9-8261-e7da27ca74e9.jpeg)
![3](https://user-images.githubusercontent.com/33349650/60245175-a7ad7a00-98d9-11e9-8bc8-5eb1d336f643.jpeg)

**Comment by mriganksingh1** [comment]
@aggarwalpulkit596 
Bug in the webpage of ICC world cup prediction. If you take the time backward of your pc and then predict then you can still predict even after the match is over.
![BOSS](https://user-images.githubusercontent.com/44446528/60361106-fd2d7800-99fa-11e9-95ad-ebc7df0dc267.jpeg)
![WhatsApp Image 2019-06-28 at 23 07 52](https://user-images.githubusercontent.com/44446528/60361125-07e80d00-99fb-11e9-8197-f17e8017fc87.jpeg)
As you can see that the match is over and I had changed the time to 7 a.m and I can make all the correct predictions.

**Comment by mriganksingh1** [comment]
@aggarwalpulkit596 
The same issue is with the app too I just tried and saw it.
![BOSS3](https://user-images.githubusercontent.com/44446528/60362158-d6247580-99fd-11e9-92b7-d6274e0cc2e5.jpeg)
![BOSS4](https://user-images.githubusercontent.com/44446528/60362167-dae92980-99fd-11e9-90c7-c85498ed9577.jpeg)

Even it is showing time left for predictions 0 but I can still make and submit it.
I just backward my mobile time.

**Comment by SaumyaSingh1** [comment]
Bug - 
ViewPager in the HomeFragment Freezes on it's own .(At "Data is the new science")

https://im4.ezgif.com/tmp/ezgif-4-4f752176b0d1.gif

**Comment by aggarwalpulkit596** [comment]
@SaumyaSingh1 there is already issue opened for this #290

**Comment by aggarwalpulkit596** [comment]
> @aggarwalpulkit596
> The same issue is with the app too I just tried and saw it.
> ![BOSS3](https://user-images.githubusercontent.com/44446528/60362158-d6247580-99fd-11e9-92b7-d6274e0cc2e5.jpeg)
> ![BOSS4](https://user-images.githubusercontent.com/44446528/60362167-dae92980-99fd-11e9-90c7-c85498ed9577.jpeg)
> 
> Even it is showing time left for predictions 0 but I can still make and submit it.
> I just backward my mobile time.

Great Work @mriganksingh1 open up this in a separate issue

**Comment by aggarwalpulkit596** [comment]
> @aggarwalpulkit596
> The same issue is with the app too I just tried and saw it.
> ![BOSS3](https://user-images.githubusercontent.com/44446528/60362158-d6247580-99fd-11e9-92b7-d6274e0cc2e5.jpeg)
> ![BOSS4](https://user-images.githubusercontent.com/44446528/60362167-dae92980-99fd-11e9-90c7-c85498ed9577.jpeg)
> 
> Even it is showing time left for predictions 0 but I can still make and submit it.
> I just backward my mobile time.

Great Work @mriganksingh1 open up this in a separate issue

**Comment by sunil-kumarr** [comment]
there is still an issue in viewpager on home fragment as there was a problem in smoothness #289 said to be resolved in #292 .
But https://github.com/sunil-kumarr/CBOnlineApp/blob/development/viewpager%20cbonline%20GIF.gif  when viewpager animation is getting stuck as shown in gif

**Comment by Sachindrck** [comment]
UI bug - The content of the button, Login with OTP not visible, maybe kind of content overflow.

![imageedit_2_7173144064](https://user-images.githubusercontent.com/46827344/81970431-29ff7380-963d-11ea-8516-05a08f3acf6d.jpg)

**Comment by aggarwalpulkit596** [comment]
This is a WebView Error not related to Android Native

**Comment by Sachindrck** [comment]
okay @aggarwalpulkit596
