### ISSUE TITLE
use Arraylist to create Relationship

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/CBOnlineApp#24]
@championswimmer bhaiya should we use ArrayList as an embedded object to create relationships among different classes rather creating this relationship manually as we are getting a nested object structure and from the api call straight forward and relationship are required when we need to manually create relationship between two seperate classes @the-dagger bhaiya your thoughts on this ?

**Comment by aggarwalpulkit596** [comment]
https://stackoverflow.com/questions/44986626/android-room-database-how-to-handle-arraylist-in-an-entity

**Comment by aggarwalpulkit596** [comment]
i'm testing this structure today if I'm able to save the values in all the tables from a single db call i think we can skip the many to many relationships because we can't directly access sections directly until we have top-level ids

**Comment by championswimmer** [comment]
> but there wouldn't be any many to many relationship required if we directly use the object getting from api 

Thumbrule of Databases - many-many relationships are not possible without mapping tables. 
Please do not forget school level SQL when doing Android. 

Do embedded ArrayLists make mapping tables ?
