### ISSUE TITLE
theme support

### ISSUE THREAD

**Issue by adityastic** [coding-blocks/CBOnlineApp#250]
**Describe the feature you'd like**
Theme Support for the Application

**Would you like to work on the issue?**
YES

**Comment by adityastic** [comment]
@aggarwalpulkit596 please allot bounty to this

**Comment by adityastic** [comment]
@aggarwalpulkit596 How do I claim 20 bounty for reporting this issue? Should I place the same link in the pull request section of the claim? Also Assign bounty to this issue plz

**Comment by adityastic** [comment]
@aggarwalpulkit596 add bounty plz

**Comment by aggarwalpulkit596** [comment]
We'll be using new daylight theme

**Comment by adityastic** [comment]
@aggarwalpulkit596 can I suggest the interface changes? I specialise in Custom Views and UI/UX for Android. Would love to help this app be the best in the market
