### ISSUE TITLE
Not able to update notes

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/CBOnlineApp#251]

**Comment by aggarwalpulkit596** [comment]
@adityastic Please fix this ASAP I need to release an update today

**Comment by aggarwalpulkit596** [comment]
Even videos aren't playing this is what I was telling you to check first

**Comment by adityastic** [comment]
got it, let me check.

**Comment by adityastic** [comment]
@aggarwalpulkit596 There is some issue with the response from the server:
Log:
NotesJSON: Response{protocol=h2, code=500, message=, url=https://api-online.cb.lk/api/v2/notes/1897}

**Comment by adityastic** [comment]
@aggarwalpulkit596 another test:
createNote Response: 
Response{protocol=h2, code=200, message=, url=https://api-online.cb.lk/api/v2/notes}
The Body:
CreateNotesJSON: 1902, test, com.codingblocks.onlineapi.models.ContentsId@561dccb, null, , 0.0
Note the id is **1902**
When editing the Note Response:
NotesJSON: Response{protocol=h2, code=500, message=, url=https://api-online.cb.lk/api/v2/notes/1902}

**Comment by aggarwalpulkit596** [comment]
Note OnClick is also not working

**Comment by adityastic** [comment]
@aggarwalpulkit596 note OnClick works, I get seeked to the duration when the Note was created. Please give me the steps to reproduce the issue, we might be on different pages here

**Comment by aggarwalpulkit596** [comment]
Yea it's working i forgot that it needs to same video
