### ISSUE TITLE
crash on clicking challenges section in videoplayeractivity

### ISSUE THREAD

**Issue by adityastic** [coding-blocks/CBOnlineApp#252]
**Describe the bug**
The App crashes when clicking on challenges section

**Logs**
`
    java.lang.ClassCastException: androidx.fragment.app.Fragment$3 cannot be cast to android.content.Context
        at com.codingblocks.cbonlineapp.adapters.SectionDetailsAdapter$CourseViewHolder$bindView$1$8.onClick(SectionDetailsAdapter.kt:396)
`

**Additional context**
Someone tried to cast the context as activity

**Would you like to work on the issue?**
YES

**Comment by aggarwalpulkit596** [comment]
I'm moving all click listeners to fragment so need of this
