### ISSUE TITLE
Video Player is not working correctly in mobile with aspect ratios 18:9 or 19.5:9

### ISSUE THREAD

**Issue by sarthak-1998** [coding-blocks/CBOnlineApp#267]
**Describe the bug**
when a video is being played in newer smartphones with aspect ratios other than 16:9, controls of player such as pause/play and seek bar gets cut in the screen. 

To  @aggarwalpulkit596 
1. Go to 'My courses'
2. Click on 'resume and then on any video'
3. See error !

**Expected behavior**
A clear and concise view of the player controls.

**Screenshots**
developer doesn't allow this

**Comment by adityastic** [comment]
can confirm, and would like to work on this

**Comment by aggarwalpulkit596** [comment]
@adityastic I recently pushed a dirty fix for this you can improvise that or find an actual fix occupied with something new for the app :)

**Comment by adityastic** [comment]
@aggarwalpulkit596 I am currently busy with something, I will definitely get to something by night. I will keep you posted

**Comment by adityastic** [comment]
Fixed :)

**Comment by adityastic** [comment]
@aggarwalpulkit596 Sorry for being late, I was busy the last two days. I've fixed the issue. Now it will work for any aspect ratio regardlessly.

**Comment by aggarwalpulkit596** [comment]
@adityastic youtube video are crashing in full-screen fix that

**Comment by adityastic** [comment]
> @adityastic youtube video are crashing in full-screen fix that

Let me check
