### ISSUE TITLE
Recyclerview of "Previous Attempts" in AboutQuizFragment should more responsive

### ISSUE THREAD

**Issue by SaumyaSingh1** [coding-blocks/CBOnlineApp#274]
**Describe the feature you'd like**
To @aggarwalpulkit596 
In the app in the AboutQuizFragment , if we press START QUIZ and after answering a few questions we press BACK button then our answers are saved as previous attempts. we get a recyclerview of previous attempts.  If i restart the quiz with the saved draft and press BACK without answering any new question then also a new draft is created. 

1.A large number of drafts (some of them being same)  create a mess .
 **Being a user, i want to delete some of my previous attempts on long pressing that particular draft** **Each row in previous attempt should handle longclicklisteners.** 

2. If new draft is same as the previous one then should be merged in one ? I guess !

 

**Screenshots**
![image](https://user-images.githubusercontent.com/46818757/59146471-3da56180-8a0c-11e9-98bb-e351daff15d1.png)

**Comment by aggarwalpulkit596** [comment]
This is no api for that
