### ISSUE TITLE
Duplicate entries in QuizActivity.

### ISSUE THREAD

**Issue by adityastic** [coding-blocks/CBOnlineApp#275]
**Describe the issue**

The recycler view list in the QuizFragment does not get cleared, instead the items are added into the earlier list everytime. We need to clear the list on fetching the attempts

![](https://i.imgur.com/HHLABAw.jpg)
![](https://i.imgur.com/M3jOmYD.jpg)

**Would you like to work on this**
YES

**Comment by adityastic** [comment]
@aggrawalpulkit596 assign bounty

**Comment by aggarwalpulkit596** [comment]
I'm sorry I didn't get you here what's the issue can you explain a little bit more

**Comment by adityastic** [comment]
@aggarwalpulkit596 the attemplist gets created on activitycreated in aboutquizfragment. When you enter a quiz and press back, the list gets reinitialised and the items get appended again, we should clear the list and then append the items
