### ISSUE TITLE
Free Tag in few(premium) section of Paid Course

### ISSUE THREAD

**Issue by SaumyaSingh1** [coding-blocks/CBOnlineApp#277]
**Describe the bug**
For a course i am using trial and paid both the versions .

![image](https://user-images.githubusercontent.com/46818757/59148784-abf91c80-8a2a-11e9-8f36-fb751a456d1b.png)

**In both the versions , Free Tag for premium courses is available . If the user is using the paid course then entire course is free , no use of Free Tag on few of the sections .**

TRIAL VERSION ✔
![image](https://user-images.githubusercontent.com/46818757/59148826-0eeab380-8a2b-11e9-9c63-5f0e6103ff07.png)

PAID COURSE (FREE TAG FOR FEW SECTION ,NOT NEEDED ❌)
![image](https://user-images.githubusercontent.com/46818757/59148834-32156300-8a2b-11e9-9454-cb9030a36e75.png)

**Expected behavior**

In the Paid Course , since entire course is free so i don't want free tag in only few sections.

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Redmi Note 4|

**Comment by SaumyaSingh1** [comment]
@championswimmer @aggarwalpulkit596  please add the bounty

**Comment by SaumyaSingh1** [comment]
@aggarwalpulkit596  Do we get bounties for opening new issues?

**Comment by aggarwalpulkit596** [comment]
Yes 20 bounty each for opening an issue
