### ISSUE TITLE
Facebook login button is not working in app

### ISSUE THREAD

**Issue by joeedwin** [coding-blocks/CBOnlineApp#297]
**Describe the bug**

Facebook login is not working in app
On pressing FB login button it shows "cannot read property of null"

**To Reproduce**

open app and press Facebook login button

**Expected behavior**

Facebook login should  work in mobile app

**Screenshots**

![WhatsApp Image 2019-06-18 at 8 51 06 PM](https://user-images.githubusercontent.com/26297616/59697115-e9b82b00-920a-11e9-8485-17980502f55e.jpeg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |      Redmi 5|
|Android Version|   7.1.2    |

**Would you like to work on the issue?**
  yes
<!-- Please let us know if you can work on it or the issue should be assigned to someone else. -y->
- Yes
- 
-

**Comment by adityastic** [comment]
this might be a website issue

**Comment by aggarwalpulkit596** [comment]
Yeah this is a website issue not app issue

**Comment by aggarwalpulkit596** [comment]
Create an issue oneauth
