### ISSUE TITLE
Fatal Exception: android.database.sqlite.SQLiteConstraintException

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/CBOnlineApp#305]
**Logs**
com.codingblocks.cbonlineapp.database.CourseRunDao_Impl.insertNew + 438 (CourseRunDao_Impl.java:438)
com.codingblocks.cbonlineapp.database.CourseRunDao_Impl.insertNew + 22 (CourseRunDao_Impl.java:22)
com.codingblocks.cbonlineapp.viewmodels.HomeViewModel$fetchRecommendedCourses$1.invoke + 78 (HomeViewModel.java:78)
com.codingblocks.cbonlineapp.viewmodels.HomeViewModel$fetchRecommendedCourses$1.invoke + 19 (HomeViewModel.java:19)
com.codingblocks.cbonlineapp.extensions.RetrofitHelperKt$retrofitCallback$1.onResponse + 10 (RetrofitHelperKt.java:10)
retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$1.run + 83 (DefaultCallAdapterFactory.java:83)

**Comment by adityastic** [comment]
I would like to take this issue

**Comment by adityastic** [comment]
Can you tell me the steps to reproduce

**Comment by aggarwalpulkit596** [comment]
Actually the upcoming issues will be coming straight from crashyltics so  can't tell you what's wrong with them you have figure it out yourself

**Comment by adityastic** [comment]
Hmm, ok. Let me try to reproduce it
