### ISSUE TITLE
'Chat on WhatsApp' option not working

### ISSUE THREAD

**Issue by nitya72** [coding-blocks/CBOnlineApp#306]
**Describe the bug**
On clicking 'chat on whatsapp' option from navigation menu it displays toast 'Please install whatsapp' even though I have whatsapp installed on my device.

**To Reproduce**
1. Go to Navigation menu from Home Activity.
2. Click on 'Chat on WhatsApp'
4. Displays toast: 'Please install whatsapp'

**Screenshots**
![Screenshot_20190619-200446](https://user-images.githubusercontent.com/32269132/59903374-7129b800-941e-11e9-8c18-2ac245e29fde.png)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Honor 6X|
|Android Version|Nougat 7.0   |

**Would you like to work on the issue?**
- [x] Yes
- [ ] No
- Other:

**Comment by nitya72** [comment]
@aggarwalpulkit596  issue is uncertain, sometimes it's working.

**Comment by aggarwalpulkit596** [comment]
Code doesn't work that way either it is working or it is not and bdw it isn't working I've checked

**Comment by anubhav11march** [comment]
@aggarwalpulkit596 I have come up with a solution and I am creating a pull request.
