### ISSUE TITLE
Implement Paging in All Course/My Course Fragment

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/CBOnlineApp#310]
Use Paging library for this which is a part of jetpack components

**Comment by raystatic** [comment]
I would like to take this

**Comment by anubhav11march** [comment]
@adityastic  Can I take this?

**Comment by raystatic** [comment]
@anubhav11march i am working on this already

**Comment by sukhbeer** [comment]
@aggarwalpulkit596 if this issue is still open?
Can I work on this?

**Comment by aggarwalpulkit596** [comment]
Yes go ahead
