### ISSUE TITLE
Crash In PDF Activity

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/CBOnlineApp#311]
**Describe the feature you'd like**
Unable to destroy activity {com.codingblocks.cbonlineapp/com.codingblocks.cbonlineapp.activities.PdfActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Handler android.app.FragmentHostCallback.getHandler()' on a null object reference

**Comment by adityastic** [comment]
I would like to take this

**Comment by anubhav11march** [comment]
@adityastic  Can I take this?

**Comment by adityastic** [comment]
@anubhav11march I'll be working on it today night. If you can finish it before 1 am, drop a pr

**Comment by anubhav11march** [comment]
Alright, thanks.
