### ISSUE TITLE
Crash in Home Activity

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/CBOnlineApp#312]
**Describe the feature you'd like**
Unable to start activity ComponentInfo{com.codingblocks.cbonlineapp/com.codingblocks.cbonlineapp.activities.HomeActivity}: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class androidx.viewpager.widget.ViewPager$i instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/0x8. Make sure other views do not use the same id.

**Comment by raystatic** [comment]
I will take this

**Comment by anubhav11march** [comment]
@adityastic  Can I take this?

**Comment by raystatic** [comment]
@anubhav11march I am already on it
