### ISSUE TITLE
Value of number of sixes and score interchanged in predictions section

### ISSUE THREAD

**Issue by ayushns9** [coding-blocks/CBOnlineApp#314]
**Describe the bug**

The values for number of sixes and score of winning team is interchanged on the mobile app in the world cup prediction offers section.

**To Reproduce**

1. Go to the predictions section on mobile app.
2. Make any prediciton.
3. See the error.

**Expected behavior**

The number of sixes should have been in the sixes section and same for the score.

**Screenshots**

![Screenshot_20190627-124349](https://user-images.githubusercontent.com/34533741/60246389-37542800-98dc-11e9-8fc3-6f8734ee0c2b.jpg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |OnePlus 5|
|Android Version|  Android 9  |

**Comment by anubhav11march** [comment]
I would like to work on this.

**Comment by mriganksingh1** [comment]
I would also like to work on this.

**Comment by adityastic** [comment]
@mriganksingh1 I'll work on it tonight

**Comment by anubhav11march** [comment]
@adityastic I'm already working on this.
