### ISSUE TITLE
Improvise Doubts Section In Course Consumption Page

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/CBOnlineApp#320]

**Comment by adityastic** [comment]
I'd like to work on this. Please provide more info on the expected interface

**Comment by aggarwalpulkit596** [comment]
Make it similar to web

**Comment by adityastic** [comment]
@aggarwalpulkit596 can you link me the api documentation. I need to get the image and the doubt message from the api. Current Doubts API only returns the title, username, date and id as a TopicItem

**Comment by adityastic** [comment]
@aggarwalpulkit596 where can i find the documentation for https://api-online.cb.lk/api/. I need to get the profile-imagelink, doubt message. Currently the Api gives me title, date , id and username as TopicsItem

**Comment by aggarwalpulkit596** [comment]
There is no documentation for that you need to inspect the website have to check the response there

**Comment by adityastic** [comment]
@aggarwalpulkit596 for some reason https://api-online.cb.lk/api/v2/courses/doubts/{doubtid} does not return the same result as in the website. The CreatedBy field is null for some reason. Please give me an update asap, Thanks

**Comment by adityastic** [comment]
@aggarwalpulkit596 any updates?

**Comment by adityastic** [comment]
@aggarwalpulkit596 did you find out the cause?

**Comment by aggarwalpulkit596** [comment]
Yeah you need to make a seperate call to discord server to fetch the details

**Comment by adityastic** [comment]
@aggarwalpulkit596 discord server?

**Comment by adityastic** [comment]
@aggarwalpulkit596 Im not sure where do I need to ping to get the doubts from https://discuss.codingblocks.com/ . Can you explain in detail the call which needs to be made to discord server?
