### ISSUE TITLE
Add Option to Generate Course Completion Certificate

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/CBOnlineApp#321]

**Comment by adityastic** [comment]
I'd like to take this issue

**Comment by adityastic** [comment]
@aggarwalpulkit596 there seems to be an option to generate certificate in the app currently

**Comment by aggarwalpulkit596** [comment]
There's no network call/check is done I've only added a layout you can still work upon on that if you want to

**Comment by adityastic** [comment]
@aggarwalpulkit596 on it

**Comment by adityastic** [comment]
@aggarwalpulkit596 I'm not able to inspect the certificate as I havent purchased any courses. I'm not able to complete 90% in any course and not able to see the difference in a normal response and an able to generate response. Any idea how I can log the response?

**Comment by aggarwalpulkit596** [comment]
Closed via #0d258c6
