### ISSUE TITLE
 Predictions submit even after time passes

### ISSUE THREAD

**Issue by mriganksingh1** [coding-blocks/CBOnlineApp#324]
**Describe the bug**
ICC World Cup Predictions, we can make predictions even after submitting period is over.

**Expected behavior**
We should not be able to make predictions after predictions period is over by any way or any means.

**Logs**
In this, I have just changed my mobile time to 7:00 a.m after the match is over and i am able to make predictions.

**Screenshots**
![BOSS3](https://user-images.githubusercontent.com/44446528/60482271-62f55a80-9cae-11e9-884c-1c0f1844bce2.jpeg)
![BOSS4](https://user-images.githubusercontent.com/44446528/60482274-6557b480-9cae-11e9-96b1-dd54fe6326b3.jpeg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |A7 (2018)
|Android Version| Android 9 Pi

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other:

**Comment by mriganksingh1** [comment]
@aggarwalpulkit596 how to claim bounty points for this issue?

**Comment by sukhbeer** [comment]
@mriganksingh1 do you work on that issue?

**Comment by mriganksingh1** [comment]
@sukhbeer nope

**Comment by mriganksingh1** [comment]
@aggarwalpulkit596 please put BOSS label on it
