### ISSUE TITLE
Scrolling is not smoother in jobs Activity

### ISSUE THREAD

**Issue by iamspathan** [coding-blocks/CBOnlineApp#355]
**Describe the bug**

When scrolling down jobs in Recycler View, scrolling is not free as normal. 

**To Reproduce**

**Screenshots**
![Jobs Scrolling](https://drive.google.com/uc?export=view&id=1lbXKC8PXU2-yyWXU2Sk5jJ-rctTX1bxD)

**Smartphone Info:**
|Device -> Tecno Camon I|
|Android Version -> Nougat 7.0  |

**Would you like to work on the issue?**

- [*] Yes
- [] No
- Other:

**Comment by rajput2122** [comment]
Can i work on this issue?
