### ISSUE TITLE
Double action bar in settings activity

### ISSUE THREAD

**Issue by liveHarshit** [coding-blocks/CBOnlineApp#414]
<p align="center">
<img src="https://user-images.githubusercontent.com/27783786/66103064-23eae400-e5d2-11e9-9f89-853b3e2e612d.png" height = "480" width="270"> 
</p>

**Would you like to work on the issue?**
good-first-issue

**Comment by aggarwalpulkit596** [comment]
Go ahead

**Comment by aggarwalpulkit596** [comment]
There is a double bar in QuizActivity as well update there as well

**Comment by aggarwalpulkit596** [comment]
Yes

**Comment by rob729** [comment]
@aggarwalpulkit596 Can I work on this issue?

**Comment by liveHarshit** [comment]
> Go ahead

I have marked is as a good first issue.
