### ISSUE TITLE
About_instructer_section_In_card_view_of_courses

### ISSUE THREAD

**Issue by ashishlalwani582** [coding-blocks/CBOnlineApp#425]
text is out of bounds in this section 
-I
![coding_block_app_issue](https://user-images.githubusercontent.com/42974546/66344581-de307180-e96b-11e9-9577-84271701ca4d.png)
![Coding_blocks_app_issue](https://user-images.githubusercontent.com/42974546/66344583-de307180-e96b-11e9-867c-a5ad4b8b4979.png)

 would like to work on these issues Yes

**Comment by rob729** [comment]
@aggarwalpulkit596 Can I work on this issue?
