### ISSUE TITLE
Missing License section in Readme.md

### ISSUE THREAD

**Issue by jddeep** [coding-blocks/CBOnlineApp#428]
Missing "License" section in the Readme file.

Include the License details of this project in its documentation.
This should be present like other substantial open source projects out there.

**Comment by jddeep** [comment]
@aggarwalpulkit596 @championswimmer  Can I work on this?

**Comment by aggarwalpulkit596** [comment]
GO ahead

**Comment by ThiagoWhispher** [comment]
Hi @jddeep @aggarwalpulkit596 
I saw that some of your repositories did not contain the readme license link.
So I decided to create an issue (like [here](https://github.com/coding-blocks/DigitalOceanApp/issues/125) ) and solve it based on that, could you take a look? I wanted to contribute something to get my swags at the Hacktoberfest event

**Comment by jddeep** [comment]
@ThiagoWhispher Before making a PR. Please see if a PR for the same issue is opened or not. A PR is already opened for this issue at #429 . Please keep this in mind while contributing to projects. Thanks.

**Comment by ThiagoWhispher** [comment]
Hi @jddeep 
I'm sorry, I fumbled and ended up doing this duplicate work (I will close the duplicate PR), but I made a similar contribution in another repository ( [here](https://github.com/coding-blocks/DigitalOceanApp/pull/126) ) could you take a look and check if it is valid?
