### ISSUE TITLE
Some courses on the home screen carousel overflow the bounds

### ISSUE THREAD

**Issue by harshshinde07** [coding-blocks/CBOnlineApp#468]
**Description**

Some courses on the home screen carousel overflow their bounds due to extra course information.

**Screenshots**

<img src="https://user-images.githubusercontent.com/25999879/67486350-83945680-f689-11e9-8449-ea087367ab9a.png" height="256">

**Would you like to work on the issue?**

- [ ] Yes
- [x] No
- Other:

**Comment by aman0408** [comment]
Can I look into this?

**Comment by harshshinde07** [comment]
@aman0408  ya go ahead. Just comment that you're working on this so that no one takes up the same issue.

**Comment by aman0408** [comment]
Okay. I'm trying to work on it

**Comment by aman0408** [comment]
Could you tell me which phone did you get this issue on? I am unable to reproduce this error on a 5.0" or a 5.5" screen size

**Comment by harshshinde07** [comment]
Device: Lenovo K8 Note
Android version: 8.0
It also has 5.5" screen

**Comment by aman0408** [comment]
I am unable to reproduce this error on Oneplus 5 and pixel 2 emulator.

**Comment by harshshinde07** [comment]
Maybe it's the PPI issue? Can you please share how it looks in your case?
