### ISSUE TITLE
Add Support to Buy Extension/Revision Pack

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/CBOnlineApp#648]

**Comment by jddeep** [comment]
@aggarwalpulkit596 I would like to work on this.

**Comment by codekaust** [comment]
@aggarwalpulkit596 can you post a bit details about this issue. I would like to work on this.

**Comment by prathamk22** [comment]
Can I work on this issue??

**Comment by aggarwalpulkit596** [comment]
Go ahead

**Comment by aggarwalpulkit596** [comment]
@jddeep @codekaust @prathamk22 i will only assign one task to one person so if you are not working on a task at a particular time just comment that you won't be working on it

**Comment by PiyushSharma99** [comment]
@aggarwalpulkit596  He(@jddeep ) will be working on it , as there is some network issue in his area.

**Comment by prince-09** [comment]
Can i  take this? @aggarwalpulkit596

**Comment by jddeep** [comment]
@aggarwalpulkit596 Please can you let me know, the API endpoints so that i can set the content in the view accordingly without hardcoding.

**Comment by aggarwalpulkit596** [comment]
For that you need to explore the website on your own
