### ISSUE TITLE
ExpandableTextView trims initial words

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/CBOnlineApp#655]
**Describe the bug**
ExpandableTextView replaces 10 letters after the first 20 first words

**Comment by iamspathan** [comment]
> **Describe the bug**
> ExpandableTextView replaces 10 letters after the first 20 first words

Once you click on textview, after **20 characters** the next **14 characters** replace to (...).

**Comment by aggarwalpulkit596** [comment]
![Screenshot_20200508-032736](https://user-images.githubusercontent.com/29139786/81348568-ee642700-90db-11ea-9716-5795fc8c06c3.jpg)
For references see this

**Comment by NitishGadangi** [comment]
I would like to work on this

**Comment by aggarwalpulkit596** [comment]
Go ahead 👍

**Comment by prince-09** [comment]
can I work on this? @aggarwalpulkit596

**Comment by NitishGadangi** [comment]
I am still working on it
Feel free to take, if I don't make a pull request in next two days

**Comment by aggarwalpulkit596** [comment]
Fixed via https://github.com/coding-blocks/CBOnlineApp/commit/e4723fdcfd515df017a803a3e093929bf00daf15
