### ISSUE TITLE
Make Chip Group Horizontally Scrollable

### ISSUE THREAD

**Issue by iamspathan** [coding-blocks/CBOnlineApp#661]
Item Track Card consist a Chip group for multiple career options chips. It's not scrollable when multiple chip items arrise.
<img src="https://user-images.githubusercontent.com/31301757/81357208-a69bca80-90f0-11ea-9d85-3fb6e705cb64.jpg" alt="gif" width="300px" height="400px">

**Comment by aggarwalpulkit596** [comment]
Always add screenshots for view related bugs

**Comment by iamspathan** [comment]
Comment updated with screenshot

**Comment by prathamk22** [comment]
Can I work on this issue??
