### ISSUE TITLE
Add empty view for doubts in video player

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/CBOnlineApp#663]

**Comment by jddeep** [comment]
I'll take up this one @aggarwalpulkit596 :)

**Comment by prathamk22** [comment]
Can I work on this issue?

**Comment by aggarwalpulkit596** [comment]
@jddeep is already working on this i guess ?

**Comment by prathamk22** [comment]
> I'll take up this one @aggarwalpulkit596 :)

Are you working on this issue buddy?? If not can I take up this one?

**Comment by jddeep** [comment]
@prathamk22 Yes i m on it

**Comment by jddeep** [comment]
@aggarwalpulkit596 shouldn't the bounty on this one should be 200 similar to #662
