### ISSUE TITLE
Add option to rate/review a course

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/CBOnlineApp#664]

**Comment by aryangulati** [comment]
tell me more about this issues

**Comment by aggarwalpulkit596** [comment]
You need to create an option just like website to review/rate the course also if there exist one already then option to edit that one

**Comment by jashasweejena** [comment]
Can I take up this issue?

**Comment by aggarwalpulkit596** [comment]
Go ahead

**Comment by prince-09** [comment]
Can I take this issue?

**Comment by prathamk22** [comment]
Is someone working on this issue?? If not can I take up this one??

**Comment by aggarwalpulkit596** [comment]
@prathamk22 feel free to take this

**Comment by jashasweejena** [comment]
@aggarwalpulkit596 @prathamk22 Since I haven't started working on this issue, can I move on to another issue?

**Comment by aggarwalpulkit596** [comment]
Yes you can

**Comment by prince-09** [comment]
@aggarwalpulkit596 I have commented first on this issue you should assign it to me

**Comment by aggarwalpulkit596** [comment]
Prince there wasn't any activity for 5 days from your end and there is buffer of 2 days if you want to work on any issues you can take a week to complete the issue but there should be an initial activity within 2 days so that a particular issue is not blocked

**Comment by jashasweejena** [comment]
Is anyone working on this issue currently?

**Comment by aggarwalpulkit596** [comment]
@jashasweejena feel free to take this one

**Comment by jashasweejena** [comment]
> @jashasweejena feel free to take this one

Okay, sure! Will keep updating about the progress.

**Comment by hardik-dua** [comment]
@jashasweejena are you working on this? is you are working on any another issue as well pls let me know I would take this one then..

**Comment by jashasweejena** [comment]
> @jashasweejena are you working on this? is you are working on any another issue as well pls let me know I would take this one then..

Yes, @hardik0899. I am working :)

**Comment by prathamk22** [comment]
@jashasweejena are you working on it or can I take it??

**Comment by prathamk22** [comment]
Taking this up
