### ISSUE TITLE
Remove Course from Cart.

### ISSUE THREAD

**Issue by iamspathan** [coding-blocks/CBOnlineApp#665]
**Describe the feature you'd like**
In CheckoutDetailsFragmnet there should be a button to **remove the current item** or **clear cart**. 

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other:

**Comment by hardik-dua** [comment]
Yes,I would like to work on this issue. Please assign.

**Comment by hardik-dua** [comment]
@iamspathan what will be the bounty for this issue??

**Comment by aggarwalpulkit596** [comment]
@hardik0899 added bounty

**Comment by hardik-dua** [comment]
@aggarwalpulkit596 Ok Sir
