### ISSUE TITLE
Verify button overlapping OTP edit text while typing 

### ISSUE THREAD

**Issue by prathamk22** [coding-blocks/CBOnlineApp#668]
![WhatsApp Image 2020-05-10 at 22 08 55](https://user-images.githubusercontent.com/32957484/81505184-1f766e80-930b-11ea-8283-a15843600db5.jpeg)

When OTP screen opens, and when we click on the edit text, verify button overlaps with the edit text and not able to view the edit text which makes difficult to view the edit text

Yes I would like to work on this issue.

**Comment by prathamk22** [comment]
I want to work on this issue.

**Comment by aggarwalpulkit596** [comment]
Nice go ahead

**Comment by prathamk22** [comment]
@aggarwalpulkit596 can you please add the BOSS tag in it and the bounty.
