### ISSUE TITLE
Bottom Navigation Bar contents shrinks.

### ISSUE THREAD

**Issue by hardik-dua** [coding-blocks/CBOnlineApp#672]
![Screenshot_2020-05-11-11-25-12-17](https://user-images.githubusercontent.com/36165541/81528517-867f3c00-937a-11ea-972f-d02d0031d3be.png)

As shown in the pic the bottom navigation contents like My Courses and dashboard got shrinked.

**Comment by hardik-dua** [comment]
@aggarwalpulkit596  if its a major bug then pls assign Bounty for this.

**Comment by aggarwalpulkit596** [comment]
Assigned @hardik0899

**Comment by praj1wal** [comment]
Can I work on this issue?

**Comment by aggarwalpulkit596** [comment]
@hardik0899  will  be working on this one you can take any other issue or you can create one if you find any

**Comment by adiig7** [comment]
@hardik0899 bro have you done this issue?

**Comment by hardik-dua** [comment]
@adiig7 yes bro trying to identify whats happening for smaller screen. If I could'nt get some solution I will pass on this issue to you.

**Comment by adiig7** [comment]
@hardik0899 yeah bro take your time :)
If anyhow you are not able to do, let me know. :)

**Comment by RM07** [comment]
Can I work on this issue

**Comment by adiig7** [comment]
@aggarwalpulkit596 sir its been 5 days and no PR hasn't been made, please assign this to me.

**Comment by aggarwalpulkit596** [comment]
You can start working on this one

**Comment by hardik-dua** [comment]
> @aggarwalpulkit596 sir its been 5 days and no PR hasn't been made, please assign this to me.

@adiig7 bro I have opened a PR.

**Comment by adiig7** [comment]
@hardik0899 okay bro cool.

**Comment by payalmangla17** [comment]
i want to work on this issue
