### ISSUE TITLE
Remove 'My purchases' if not logged in 

### ISSUE THREAD

**Issue by praj1wal** [coding-blocks/CBOnlineApp#674]
If the user is not logged in, then the my purchases button should not be visible,as it is redirecting to a blank screen.

![WhatsApp Image 2020-05-12 at 16 23 36](https://user-images.githubusercontent.com/48339444/81676387-641a1b00-946d-11ea-9dcc-38bb662303f5.jpeg)
![WhatsApp Image 2020-05-12 at 16 23 36 (1)](https://user-images.githubusercontent.com/48339444/81676457-7bf19f00-946d-11ea-84d6-f7ced5a9ce89.jpeg)

**Comment by praj1wal** [comment]
I want to take this issue

**Comment by adiig7** [comment]
Hey @praj1wal how is it going with this issue?

**Comment by Ayush7-BIT** [comment]
I can work on this issue?

**Comment by adiig7** [comment]
@praj1wal if you are not working on this issue, I can work on it. Please update me if you are doing or not?

**Comment by praj1wal** [comment]
@adiig7  I am done with this issue, will send a PR in a while.
