### ISSUE TITLE
Share via whatsapp button not working

### ISSUE THREAD

**Issue by praj1wal** [coding-blocks/CBOnlineApp#675]
Share via whatsapp button is not working, same is the case with 'more' option.

![WhatsApp Image 2020-05-12 at 17 43 05](https://user-images.githubusercontent.com/48339444/81689712-28d11980-9478-11ea-95fb-1b2af6717f53.jpeg)

**Comment by aggarwalpulkit596** [comment]
There is a from backend because of this it is blocked will let you know once done

**Comment by saloniankita** [comment]
Can I work on it ?

**Comment by aggarwalpulkit596** [comment]
This is on hold for now
