### ISSUE TITLE
Title bar name doesn't change when tabs are changed

### ISSUE THREAD

**Issue by HaripriyaB** [coding-blocks/CBOnlineApp#676]
**Describe the bug**
As a user, When I switch tabs, the title bar don't change from "Dashboard". For more details refer screenshots.

**To Reproduce**
1. Go to Dashboard
2. Click on any other tab
3. See that title bar doesn't change the name. 

**Expected behavior**
The title bar name need to change according to the switched tab title.

**Screenshots**
![Screenshot_2020-05-12-21-36-33-34_7a48d95313daa0d8bdbf7891041c354f](https://user-images.githubusercontent.com/34762451/81718754-c0932f80-9499-11ea-903e-ffc72cc98c62.png)

![Screenshot_2020-05-12-21-36-38-89_7a48d95313daa0d8bdbf7891041c354f](https://user-images.githubusercontent.com/34762451/81718765-c6891080-9499-11ea-92f9-dd2ebe858e7e.png)

![Screenshot_2020-05-12-21-36-44-11_7a48d95313daa0d8bdbf7891041c354f](https://user-images.githubusercontent.com/34762451/81718773-c9840100-9499-11ea-8952-454d15e50ade.png)

![Screenshot_2020-05-12-21-36-48-89_7a48d95313daa0d8bdbf7891041c354f](https://user-images.githubusercontent.com/34762451/81718781-cb4dc480-9499-11ea-9e13-15fd89b92f1c.png)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Oppo A9 2020|
|Android Version|Pie 9.0     |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No

**Comment by HaripriyaB** [comment]
@aggarwalpulkit596  Pls assign bounties if this is a valid issue.

**Comment by adiig7** [comment]
Can I take up this issue?

**Comment by HaripriyaB** [comment]
> 
> 
> Can I take up this issue?

I've Already marked yes for working on the issue.
