### ISSUE TITLE
Login with OTP text on button not visible clearly

### ISSUE THREAD

**Issue by HaripriyaB** [coding-blocks/CBOnlineApp#677]
**Describe the bug**

The "Login with OTP" button text is not visible from Android 9.0 Oppo A9 2020 device.

**To Reproduce**
Note: This issue may not occur for all the devices.
1. Click on login/signup from splash screen 
2. Click on login with Google button
3. See that next to login button there is another login button with incomplete text shown.
 
**Expected behavior**

Show complete "Login with OTP" text on the button

**Screenshots**
![Screenshot_2020-05-12-21-30-21-20_7a48d95313daa0d8bdbf7891041c354f](https://user-images.githubusercontent.com/34762451/81720664-56c85500-949c-11ea-9a45-833e3816a4d0.png)

**Smartphone Info:**
|               | |
|---------------|-|
|Device         |Oppo A9 2020|
|Android Version| Pie 9.0    |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No

**Comment by aggarwalpulkit596** [comment]
This is a web-view, not an application-level issues

**Comment by HaripriyaB** [comment]
@aggarwalpulkit596 Can u pls guide me which repo should I go to report this issue?
