### ISSUE TITLE
Bookmark feature is not working properly.

### ISSUE THREAD

**Issue by iamspathan** [coding-blocks/CBOnlineApp#678]
**Describe the bug**
Users are unable to add bookmarks in the video players. 

**To Reproduce**

1. Go to 'Any Enrolled Course'
2. Click on  'Any Lecture Video'
3. Click on 'Bookmark'  left of Download Button

**Expected behavior**

All the bookmarks need to be saved and shown in **My Bookmark** section of course library

**Smartphone Info:**

REALME XT (ANDROID 10)

**Additional context**

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other:

**Comment by CapTen101** [comment]
I want to work on this. I'm on it @iamspathan

**Comment by CapTen101** [comment]
@aggarwalpulkit596 Kindly assign the bounty to this issue

**Comment by aggarwalpulkit596** [comment]
Actually I'm not sure about this issue can you confirm ?🤔

**Comment by prince-09** [comment]
@aggarwalpulkit596 can I start working on this issue if nobody is working?

**Comment by CapTen101** [comment]
I'm already on this issue
