### ISSUE TITLE
Profile Image not appearing in profile screen though in app drawer header

### ISSUE THREAD

**Issue by jddeep** [coding-blocks/CBOnlineApp#681]
**Describe the bug**
Profile photo not set if logged in from social media. For instance i logged in from GitHub. The drawer header showed the photo but the profile screen didn't.

**To Reproduce**
1. Login using GitHub/social
2. Open app drawer
3. Profile image appears there but then go to View profile.

**Expected behavior**
The same image should appear there.

**Screenshots**
<img src="https://user-images.githubusercontent.com/43133646/81772064-72fedd00-9502-11ea-8de1-71a750d65e29.png" width=300/>
<img src="https://user-images.githubusercontent.com/43133646/81772096-84e08000-9502-11ea-8add-56d5f56efaa8.png" width=300/>

**Smartphone Info:**
Realme 5 Pro

**Would you like to work on the issue?**

- [x] Yes
- [ ] No

**Comment by jddeep** [comment]
@aggarwalpulkit596 Reviews here please.

**Comment by adiig7** [comment]
Can I work on this issue?

**Comment by aggarwalpulkit596** [comment]
@jddeep if you're working on any task please let me know otherwise I'll it somebody else

**Comment by prince-09** [comment]
@aggarwalpulkit596  Can I work on this issue?

**Comment by PiyushSharma99** [comment]
@aggarwalpulkit596 ,
@jddeep has worked on this issue, he will send the PR as soon as his internet service resume.  (Internet services are down by government)
