### ISSUE TITLE
Incomplete social media options for logging in

### ISSUE THREAD

**Issue by jddeep** [coding-blocks/CBOnlineApp#682]
**Describe the bug**
Incomplete social media options for logging in. We have options to login using Github and Twitter as well but they aren't available on the login screen. This leads to confusion. I suggest to add the GitHub and Twitter login options as well just like in the Webview.

**To Reproduce**

1. Go to Login screen
2. Click on Google/Facebook
3. Webview gets opened and from there we can login using Twitter/FB/Google/Github

**Expected behavior**
Options for Twitter and Github should also be there in the app to avoid confusion.

**Screenshots**
<img src="https://user-images.githubusercontent.com/43133646/81772925-b9553b80-9504-11ea-82be-b9777b804273.png" width=300/>
<img src="https://user-images.githubusercontent.com/43133646/81772946-d0942900-9504-11ea-9770-9b5b2a34e125.png" width=300/>

**Smartphone Info:**
Realme 5 Pro

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by jddeep** [comment]
@aggarwalpulkit596 Reviews here please.

**Comment by aggarwalpulkit596** [comment]
It is related to webview report to frontend of website
