### ISSUE TITLE
Live Streaming on App

### ISSUE THREAD

**Issue by mnb27** [coding-blocks/CBOnlineApp#683]
**Describe the feature you'd like**

We can have live streaming feature like youtube/instagram etc.

**Screenshots**

![image](https://user-images.githubusercontent.com/52792904/81811442-3fdc3e00-9542-11ea-8548-ab54d2184b62.png)

**Additional context**

Webinars can be held through this feature and also students/faculty can volunteer and upload interesting videos regarding any common doubt.

**Would you like to work on the issue?**

I am not sure if I can add this feature because I am new to android development but surely i will try.

**Comment by aggarwalpulkit596** [comment]
Not possible
