### ISSUE TITLE
Unable to create new account

### ISSUE THREAD

**Issue by adiig7** [coding-blocks/CBOnlineApp#685]
**Describe the bug**

I'm unable to create a new account. Snack bar pops up with **retry** option

**To Reproduce**

1. Go to 'Create an account'
2. Enter the details
3. Click on proceed

**Screenshots**

![Screenshot_20200513-202933_(Debug)Coding Blocks](https://user-images.githubusercontent.com/54351909/81833439-55ab2c80-955d-11ea-872b-8653998cdb46.jpg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Samsung Galaxy M30s | 
|Android Version| Android 10   |

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other:

**Comment by CapTen101** [comment]
I would like to work on this issue

**Comment by adiig7** [comment]
@aggarwalpulkit596 please review this.

**Comment by aggarwalpulkit596** [comment]
I'm already working on this one so closing this one

**Comment by adiig7** [comment]
@aggarwalpulkit596 please do asap bcz I'm not able to make an account and therefore can't find bugs.

**Comment by aggarwalpulkit596** [comment]
@adiig7 can you try making an account from the website i will try to complete this by end of the week so till then you can find bugs

**Comment by adiig7** [comment]
@aggarwalpulkit I can but to find bugs in the android app I need to login in the app.

**Comment by aggarwalpulkit596** [comment]
@adiig7 just make an account from online.codingblocks.com and use that credentials in the app you'll be good to go and if you want a course you can enroll into any free course there are lot of them you can also enroll into a trial

**Comment by adiig7** [comment]
@aggarwalpulkit596 okay thanks
