### ISSUE TITLE
Course wishlist feature is not working.

### ISSUE THREAD

**Issue by mrwhoknows55** [coding-blocks/CBOnlineApp#686]
**Describe the bug**   

**Course Wishlist** feature is not working. 
After clicking on the wishlist button does not give any response.

**To Reproduce**

1. Go to Explore tab
2. Click on wishlist button in the course card or in the toolbar. 
3. Or click on same button in the course details toolbar. (as shown in screenshots)

**Expected behavior**

Particular course should be added in the **My Wishlist** section.

**Screenshots**

![Screenshot](https://user-images.githubusercontent.com/30384908/81840352-804db300-9566-11ea-964a-94a5ac82a2cc.gif)

**Additional context**

Similar [issue](https://github.com/coding-blocks/codingblocks.online.projectx/issues/556) on `codingblocks.online.projectx` project.

**Smartphone Info:**
|               | |
|---------------|-|
|Device         |Honor 8x|
|Android Version|Android 10 |

**Would you like to work on the issue?**
- [ ] Yes
- [ ] No
- Other:

**Comment by shivanshg240** [comment]
How to contribute in this issue

**Comment by adiig7** [comment]
Can i work on this issue?

**Comment by mrwhoknows55** [comment]
@shivanshg240 @adiig7 I'm working on this issue

**Comment by prince-09** [comment]
@mrwhoknows55 are you still working on this issue or can I take it?

**Comment by mrwhoknows55** [comment]
@prince-09 I'm working on it.

**Comment by mrwhoknows55** [comment]
@prince-09 you can work on  the issue if you want.

**Comment by AkshobhyaP** [comment]
I would like to work on this issue.

**Comment by mrwhoknows55** [comment]
@AkshobhyaP sure!

**Comment by AkshobhyaP** [comment]
@aggarwalpulkit596 as much as I can see there is no JSON or REST API for storing or retrieving favorites so how should I handle this problem. Any suggestions are welcome.

**Comment by aggarwalpulkit596** [comment]
@AkshobhyaP there is a api for as well as for retrieving the list so try to find out that thing

**Comment by prathamk22** [comment]
anyone working on it?? Or can I work on this??

**Comment by AkshobhyaP** [comment]
@prathamk22 you can work on it. I am not working on it.

**Comment by prathamk22** [comment]
@AkshobhyaP Great. Taking this up.
