### ISSUE TITLE
UI : Referral Activity WhatsApp Share Button is getting cut

### ISSUE THREAD

**Issue by root-ansh** [coding-blocks/CBOnlineApp#687]
**Describe the bug**
WhatsApp Referral button isn't working and its UI is getting cut in my device (MI A2 Android 10). Setting both button's Text size to `14sp` instead of `12sp` would probably fix it

**To Reproduce**
1. Open app ( create account/signup/browse courses)
2. Open Hamburger Menu
3. Press "invite and earn" strip at the bottom

Note: This issue only arrives if user has set the system setting  `font size` and `display size` to `default` (Mostly true for non tech audience) 

**Expected behavior**
Button should be in one line

**Logs** :NA

**Screenshots**

![image](https://user-images.githubusercontent.com/31290636/81851358-efcb9e80-9576-11ea-99e6-6a921d7a655a.png)

**Smartphone Info:**
|               | |
|---------------|-|
|Device         | MI A2|
|Android Version|Q 10    |

**Would you like to work on the issue?**

- [x] **Yes**

**Comment by root-ansh** [comment]
@aggarwalpulkit596  Can I Work on this issue?

**Comment by aggarwalpulkit596** [comment]
Go ahead 👍
