### ISSUE TITLE
Adding a "No course purchased" message in My purchase page

### ISSUE THREAD

**Issue by HaripriyaB** [coding-blocks/CBOnlineApp#689]
**Describe the feature you'd like**

When I click on My Purchases from the side navigation bar, there comes a blank white page meaning no purchases done. Instead we can have the empty view of "My Courses" page with slight editing in the text.

**Screenshots**
Current Page 
![Screenshot_2020-05-13-00-17-29-53_7a48d95313daa0d8bdbf7891041c354f](https://user-images.githubusercontent.com/34762451/81736008-8f275d80-94b3-11ea-8e54-6bc23039c9f2.png)

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

**Comment by aggarwalpulkit596** [comment]
Instead of this text use my courses empty view

**Comment by HaripriyaB** [comment]
> 
> 
> Instead of this text use my courses empty view

Yeah! Thanks for the suggestion. I'll edit the issue and start working on it.

**Comment by aadij6401** [comment]
i want to work on it.

**Comment by HaripriyaB** [comment]
@aadij6401 I have said yes to work on it so I'm working on it already :-)
