### ISSUE TITLE
Fragment explore courses opens up without changes in bottom navigation view

### ISSUE THREAD

**Issue by adiig7** [coding-blocks/CBOnlineApp#691]
**Describe the bug**

If the user hasn't bought any courses, and if the explore courses button is clicked in the my library fragment the explore courses fragment opens up but without changes in bottom navigation view.

**To Reproduce**

1. Go to 'My Library fragment'
2. Click on 'Explore courses'
3. Check Bottom Navigation View

**Expected behavior**

Bottom navigation should switch to explore fragment.

**Screenshots**

![Screenshot_20200514-043503_(Debug)Coding Blocks](https://user-images.githubusercontent.com/54351909/81881983-3341ff00-95af-11ea-8d2f-cddc4979a193.jpg)
![Screenshot_20200514-043529_(Debug)Coding Blocks](https://user-images.githubusercontent.com/54351909/81881987-35a45900-95af-11ea-845e-90b964ebb2ad.jpg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Samsung Galaxy M30s|
|Android Version|Android 10.0|

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by aggarwalpulkit596** [comment]
@adiig7 why close this one ?

**Comment by hardik-dua** [comment]
@adiig7 worked fine bro!!

**Comment by adiig7** [comment]
@hardik0899 but you can see it's not working for me. Idk why??

**Comment by hardik-dua** [comment]
@adiig7 Yeah I saw.. have to observe what's happening out there.

**Comment by adiig7** [comment]
@hardik0899 I'm working on it currently.

**Comment by hardik-dua** [comment]
Yeah Sure bro..
