### ISSUE TITLE
Picture in Picture Mode not working

### ISSUE THREAD

**Issue by prathamk22** [coding-blocks/CBOnlineApp#693]
**Describe the bug**
Picture in Picture mode is not working in CB online App

**To Reproduce**
1. Go to any course
2. Start any course
3. Click home button, it should start in picture in picture mode but it is not working

**Expected behavior**
Click home button, it should start in picture in picture mode but it is not working

Device :         Samsung J7 Prime
Android Version : Oreo 8.1
**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by prathamk22** [comment]
@aggarwalpulkit596 pls review and would like to work on it.

**Comment by aggarwalpulkit596** [comment]
Go ahead

**Comment by prince-09** [comment]
@prathamk22 is this issue solved?

**Comment by prathamk22** [comment]
> @prathamk22 is this issue solved?

Yes I have made pull request already. @aggarwalpulkit596 have to test it.
