### ISSUE TITLE
Download course don't have cancel button to cancel downloading

### ISSUE THREAD

**Issue by HaripriyaB** [coding-blocks/CBOnlineApp#694]
**Describe the bug**
As a user, I might change my mind to not download the course materials but I don't see any option to cancel the downloading process.

**To Reproduce**
1. Go to Explore Courses
2. Scroll down to Trending Now
3. Click on Java Master Course|Crux course
4. Click on "Try it for Free"
5. Go to My Courses
6. Click on Java Master Course
7. Click on Curriculum and scroll down to Section 1:Basics
8. Click any of the video download button under the Section 1 and the notification bar shows the progress bar without a cancel button

**Expected behavior**
The notification bar that shows the progress of downloading the video need to have a cancel button.

**Screenshots**
![Screenshot_2020-05-14-15-05-47-84_7a48d95313daa0d8bdbf7891041c354f](https://user-images.githubusercontent.com/34762451/81918781-9013d880-95f4-11ea-8840-c395f199fc66.png)

**Smartphone Info:**
|               | |
|---------------|-|
|Device         |Oppo A9 2020|
|Android Version|Android Pie 9.0   |

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

**Comment by aggarwalpulkit596** [comment]
Yeah this one is a must

**Comment by HaripriyaB** [comment]
@aggarwalpulkit596 So bounty points for this issue???

**Comment by altruisticdream** [comment]
yes

**Comment by HaripriyaB** [comment]
Yeah I'm working on it 👍

**Comment by thefaisalkhan** [comment]
But here by sliding or swiping it automatically it cancels download

**Comment by HaripriyaB** [comment]
> 
> 
> But here by sliding or swiping it automatically it cancels download

No @thefaisalkhan Pls check. It will anyway download even if u swipe.slide the notification.

**Comment by shivamgohri** [comment]
@HaripriyaB Please let me know your progress, it's been 2 days, if you're not working on this, I would love to take this up!

**Comment by HaripriyaB** [comment]
@shivamgohri give me time till next morning, If I don't make a PR then it's all yours.

**Comment by adiig7** [comment]
@aggarwalpulkit596 sir can I work on it?

**Comment by HaripriyaB** [comment]
This issue is quite complex. The download work is done using vdocipher external package. I tried to browse vdocipher website and find the method but there was no option to stop a download process. I tried to use a broadcast receiver and use optionsdownloader.cancel for cancelling the ongoing download process but it didn't work. If anyone wants to try pls go ahead. I tried the whole night yesterday and got no output. @aggarwalpulkit596 bhaiya pls assign anyone else From the comments.

**Comment by aggarwalpulkit596** [comment]
@shivamgohri @adiig7 both of you can try this out feel free to ask anything

**Comment by hardik-dua** [comment]
@adiig7 @shivamgohri guys are you working on this or should I take this?

**Comment by shivamgohri** [comment]
@hardik0899 You can go ahead.
