### ISSUE TITLE
Storage space tracker doesn't show the occupied space

### ISSUE THREAD

**Issue by HaripriyaB** [coding-blocks/CBOnlineApp#696]
**Describe the bug**
The storage space tracker in settings page doesn't show the occupied space in red as shown in the key below it.

**To Reproduce**
1. Download any course 
2. Go to Settings page from the side nav bar
3. See the available storage shown grey even though there is occupied space.(See Screenshot)

**Expected behavior**
The storage tracker should show red according to the downloaded files size Vs available space.

**Screenshots**
![Screenshot_2020-05-14-15-14-25-98_7a48d95313daa0d8bdbf7891041c354f](https://user-images.githubusercontent.com/34762451/81920170-72e00980-95f6-11ea-8197-f0efb21986bf.png)

**Smartphone Info:**
|               | |
|---------------|-|
|Device         |Oppo A9 2020|
|Android Version|Android Pie 9.0    |

**Comment by adiig7** [comment]
@HaripriyaB can I work on it?

**Comment by HaripriyaB** [comment]
@adiig7 I will not be working on this. So as soon as the collaborator assign bounties u can claim this issue.

**Comment by adiig7** [comment]
@HaripriyaB yup okay. 
@aggarwalpulkit596 please review this issue.

**Comment by aggarwalpulkit596** [comment]
I don't really understand whats the issue here

**Comment by HaripriyaB** [comment]
@aggarwalpulkit596 The Available space bar doesn't change according to the used space. For example 395.8MB of space is used so it has to show red from the left end of the available storage. I hope u understand now.

**Comment by adiig7** [comment]
@aggarwalpulkit596 are you understanding what's the bug here? Cz if you are then please assign bounty so that i can work on it.

**Comment by championswimmer** [comment]
It is too little to show

**Comment by HaripriyaB** [comment]
@championswimmer  Sir can you check if this issue exist? if u have access to more than 1GB of content for download then pls check. probably we can see if this issue is valid or not after that.

**Comment by hardik-dua** [comment]
@HaripriyaB are you working on this ?

**Comment by HaripriyaB** [comment]
> 
> 
> @HaripriyaB are you working on this ?

nope.

**Comment by hardik-dua** [comment]
> > @HaripriyaB are you working on this ?
> 
> nope.

Ok @HaripriyaB I want to try this one..

**Comment by hardik-dua** [comment]
@aggarwalpulkit596 Bhayia I have fixed please review the PR and let me know if there are any changes.
