### ISSUE TITLE
Clicking Explore Courses textview in Cart doesn't open up Explore fragment

### ISSUE THREAD

**Issue by adiig7** [coding-blocks/CBOnlineApp#697]
**Describe the bug**

When the user is in any fragment other than explore courses fragment, and opens cart and clicks on explore courses textview, it returns to same fragment.

**To Reproduce**

Clicking **Explore Courses** should return to **Explore** fragment.

**Screenshots**

![Screenshot_20200514-154432_(Debug)Coding Blocks](https://user-images.githubusercontent.com/54351909/81923406-3fec4480-95fb-11ea-9ffe-171dfc03dd1b.jpg)
![Screenshot_20200514-154434_(Debug)Coding Blocks](https://user-images.githubusercontent.com/54351909/81923413-41b60800-95fb-11ea-855e-48577fdc5b4c.jpg)

I'm uploading the screenshot for the time when I am on doubts fragment and clicks on cart icon and then explore courses textview and then it returns to doubts fragment.

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Samsung Galxy M30s|
|Android Version|Android 10|

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by hardik-dua** [comment]
@adiig7 are you working on this?? or can I take this one?

**Comment by adiig7** [comment]
@hardik0899 sorry bro I'm working on this.

**Comment by hardik-dua** [comment]
Fine bro..

**Comment by adiig7** [comment]
@aggarwalpulkit596 please review this and assign bounty points to it.

**Comment by prince-09** [comment]
@adiig7  are you still working on it or can I take it?

**Comment by adiig7** [comment]
@prince-09 can you please give one more day? If i don't make a PR by tomorrow night you may take it.
