### ISSUE TITLE
Fragment contents change on button click but bottom navigation view and title bar remain unchanged

### ISSUE THREAD

**Issue by adiig7** [coding-blocks/CBOnlineApp#698]
**Describe the bug**

**A.** When the user has no doubts in doubts section and **Go to Classroom** button is clicked, page jumps to dashboard fragment but the bottom navigation still remains on *Doubts*.

**B.** When user switches to *Expired Courses* in **My Courses** fragment,and if there aren't any expired courses, and the user clicks on **Explore Courses** button only the content is  changed, bottom navigation view and title bar remains same.

**To Reproduce**

**A.**
1. Go to **Doubts** fragment
2. If you have 0 doubts click on **Go to Classroom** button.

**B.**
1. Go to My Courses fragment.
2. Click on drop down menu just below the title bar.
3. Click on **Expired Courses**
4. Click on **Explore Courses** button if there aren't any Expired courses.

**Expected behavior**

**A.** Bottom navigation should switch to **Dashboard** and title bar should change too.

**B.** Bottom navigation should switch to **Explore** and title bar should change too.

**Screenshots**
**A**

![Screenshot_20200514-172204_(Debug)Coding Blocks](https://user-images.githubusercontent.com/54351909/81931982-93b15a80-9608-11ea-8cbe-2c4bfdf327b2.jpg)
![Screenshot_20200514-172209_(Debug)Coding Blocks](https://user-images.githubusercontent.com/54351909/81932008-a2980d00-9608-11ea-9eb9-6a27c415b13f.jpg)

**B**
![Screenshot_20200514-205536_(Debug)Coding Blocks](https://user-images.githubusercontent.com/54351909/81953598-7fc82180-9625-11ea-9b6c-8a52bbe0ffac.jpg)

![Screenshot_20200514-205022_(Debug)Coding Blocks](https://user-images.githubusercontent.com/54351909/81953302-24962f00-9625-11ea-80b8-0d5656000c4e.jpg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Samsung Galaxy M30s|
|Android Version|Android 10.0 |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by adiig7** [comment]
@aggarwalpulkit596 please add bounty points to this so that I can work on this.

**Comment by aggarwalpulkit596** [comment]
You can start working on this I'll assign bounties in sometime

**Comment by adiig7** [comment]
@aggarwalpulkit596 sir I have added similar kind of issues to the same, kindly assign revised bounty points, and if I find similar kind of issues, I'll add them to this issue.

**Comment by adiig7** [comment]
@aggarwalpulkit596  I have added one more issue to this existing issue, please review this if bounty points to be increased or not so that I can make a PR for this.
