### ISSUE TITLE
Dashboard of earlier enrolled course opens up when Try it for free button is clicked in any course.

### ISSUE THREAD

**Issue by adiig7** [coding-blocks/CBOnlineApp#699]
**Describe the bug**
'
When **Try it for free** button is clicked in any course, it takes you to the dashboard of earlier enrolled courses instead of the course in which you clicked **Try it for free** button.

**To Reproduce**

Clicking the button should take to the dashboard of the current course.

**Logs**

**Screenshots**

![Screenshot_20200514-175007_(Debug)Coding Blocks](https://user-images.githubusercontent.com/54351909/81935852-e68e1080-960e-11ea-93a0-f243e98af4da.jpg)
![Screenshot_20200514-175013_(Debug)Coding Blocks](https://user-images.githubusercontent.com/54351909/81935858-e8f06a80-960e-11ea-82e0-32e8547c3743.jpg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Samsung Galaxy M30s|
|Android Version|Android 10.0 |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by adiig7** [comment]
Please review this @aggarwalpulkit596 .

**Comment by KANSHUMAN42** [comment]
@aggarwalpulkit596 i would like to work on this .

**Comment by adiig7** [comment]
@KANSHUMAN42 I am already working on this.

**Comment by KANSHUMAN42** [comment]
@adiig7  ohkk i will take another one.

**Comment by adiig7** [comment]
@KANSHUMAN42 if you want to take up this issue, you may now.

**Comment by prince-09** [comment]
@adiig7 @aggarwalpulkit596 can I take this issue?

**Comment by adiig7** [comment]
@prince-09 yes i have dropped this issue you may take it if you want

**Comment by prince-09** [comment]
@adiig7  sure I will take this issue
