### ISSUE TITLE
Disordered text in Topic-Wise & Feature Comparison in Course Summary.

### ISSUE THREAD

**Issue by shivamgohri** [coding-blocks/CBOnlineApp#700]
**Describe the bug**

Disordered text is appearing in the 'Course Summary' section for the following courses:

- Java Master Course | Crux
- C++ Master Course | Launchpad
- C++ Fundamentals
- Algo++ Data Structures & Algorithms
- Java Fundamentals
- Algo.Java | Data Structures & Algorithms
and more..

**To Reproduce**
1. Go to 'Explore'
2. Click on 'the courses mentioned above'
3. Scroll down to 'Course summary and click on it'

**Expected behavior**

The text should have been ordered!
This can also be implemented by adding a button to see the 'comparisons in a structured table format'.

**Logs**

//No log details!

**Screenshots**

![Screenshot_20200514-184007 1](https://user-images.githubusercontent.com/31760456/81938514-a597fb00-9612-11ea-9656-98a1abddcc3d.jpg)
![Screenshot_20200514-183956 1](https://user-images.githubusercontent.com/31760456/81938602-c3656000-9612-11ea-92e8-113e6dd85fdb.jpg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Oneplus 6|
|Android Version|Android 10   |

**Additional context**

As far as I could understand, this summary is fetched from API, so fetched text needs to be modified. 

**Would you like to work on the issue?**

- [X] Yes
- [ ] No
- Other:

**Comment by aggarwalpulkit596** [comment]
This is a markdown and can be fixed by adding support for tables in
markdown we use a library for rendering markdowns you can look upon on it
in the codebase

**Comment by shivamgohri** [comment]
@aggarwalpulkit596 So this validates this as a bug? 
So should I start working?

**Comment by aggarwalpulkit596** [comment]
Yes you can start working on this 👍
