### ISSUE TITLE
Clicking on Explore Courses in My Courses fragment doesn't change bottom nav. view

### ISSUE THREAD

**Issue by adiig7** [coding-blocks/CBOnlineApp#702]
**Describe the bug**

Clicking on **Explore Courses** in *My Courses* fragment doesn't actually jump fragment to *Explore* fragment. It shows the content of Explore fragment but the bottom navigation view remains the same and the title bar too.

**To Reproduce**

1. Go to My Courses fragment.
2. Click on drop down menu just below the title bar.
3. Click on **Expired Courses**
4. Click on **Explore Courses** button if there aren't any Expired courses.

**Expected behavior**

Clicking on **Explore Courses** should change the fragment fully with changing the title bar and bottom navigation view too.

**Logs**

No Logs.

**Screenshots**

![Screenshot_20200514-205536_(Debug)Coding Blocks](https://user-images.githubusercontent.com/54351909/81953598-7fc82180-9625-11ea-9b6c-8a52bbe0ffac.jpg)

![Screenshot_20200514-205022_(Debug)Coding Blocks](https://user-images.githubusercontent.com/54351909/81953302-24962f00-9625-11ea-80b8-0d5656000c4e.jpg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Samsung Galaxy M30s|
|Android Version|Android 10.0|

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by aggarwalpulkit596** [comment]
These issues are not required as fixing any one of them will fix all of them so closing this one in favour of #698

**Comment by aggarwalpulkit596** [comment]
@adiig7 Also instead of opening multiple issues try fixing one at a time

**Comment by adiig7** [comment]
@aggarwalpulkit596 can I add these kind of issues to same issue and you assign final bounty points?

**Comment by aggarwalpulkit596** [comment]
Yeah that would make sense

**Comment by adiig7** [comment]
Yup I have already solved two, waiting for the contest to start.
Okay, I'll add all the issues of this kind under my earlier issue and you assign final bounty points to that. Would that work @aggarwalpulkit596 ?
