### ISSUE TITLE
A feature and some UI Issues

### ISSUE THREAD

**Issue by prince-09** [coding-blocks/CBOnlineApp#706]
**Describe the bug**
Show password option must be given. Some texts and images in the login page not aligned properly.

**To Reproduce**

1. Go to 'Login page'
2. Click on 'Click on side nav bar'

**Logs**
No Logs

**Screenshots**
![IMG_20200515_060630](https://user-images.githubusercontent.com/52371330/81999683-79f92d00-9673-11ea-9796-49e37929e5a4.jpg)
![IMG_20200515_060541](https://user-images.githubusercontent.com/52371330/81999824-fe4bb000-9673-11ea-9866-27b6046bf7c5.jpg)

**Smartphone Info:**

|Device         |redmi 5a|
|Android Version|android 7.1   |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by prince-09** [comment]
@aggarwalpulkit596

**Comment by aggarwalpulkit596** [comment]
These are web-view issues not related to android
