### ISSUE TITLE
OTP is not getting detected automatically

### ISSUE THREAD

**Issue by prathamk22** [coding-blocks/CBOnlineApp#710]
**Describe the bug**
OTP is not getting detected automatically. User have to type it on their own but it is written their that it will be detected automatically.

**To Reproduce**
1. Login with mobile
2. Enter mobile number
3. Otp will be sent
4. Recieved otp but not entered automatically

**Expected behavior**
Recieved OTP should be entered automatically if recieved at anytime

|               | |
|---------------|-|
|Device         | Samsung J7 Prime |
|Android Version| Oreo 8.1 |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by prathamk22** [comment]
@aggarwalpulkit596 please review and assign bounty.

**Comment by aggarwalpulkit596** [comment]
This won't happen for debugging apk works for prod apk
