### ISSUE TITLE
Set max value for 'Set Download Limit' to available free space

### ISSUE THREAD

**Issue by NitishGadangi** [coding-blocks/CBOnlineApp#713]
**Describe the bug**
In settings, the max value for `Set Download Limit` seek bar is set to  10.0GB by default.
It will be more intuitive if it is set based on the available Free space in the mobile

**To Reproduce**
Go to settings

**Screenshots**

![WhatsApp Image 2020-05-15 at 3 29 52 PM](https://user-images.githubusercontent.com/29014716/82038483-3b8a5f00-96c1-11ea-878b-3fd2ac3ed5f6.jpeg)

**Would you like to work on the issue?**

- [x] Yes
- [ ] No

**Comment by NitishGadangi** [comment]
@aggarwalpulkit596  bro, add bounty if eligible

**Comment by LambdaLearner** [comment]
I would like to take up this issue. How do I get started?

**Comment by NitishGadangi** [comment]
@dungeonmaster51  Sorry bro,
I have already started working on it
