### ISSUE TITLE
No onclick listeners for few emails and phone numbers in Contact us page

### ISSUE THREAD

**Issue by NitishGadangi** [coding-blocks/CBOnlineApp#714]
**Describe the bug**
In `Contact us` page `onClickListeners` are not added to a few phone numbers and emails. As a result, the user won't be able to place a call or an email directly.

**To Reproduce**

In Contact Us page try to click on below mentioned phone numbers and emails

**Expected behavior**

Should be able to open `ACTION_SENDTO `or `ACTION_DIAL `intent onClick

**Screenshots**

![WhatsApp Image 2020-05-15 at 3 42 45 PM](https://user-images.githubusercontent.com/29014716/82040463-3f6bb080-96c4-11ea-8a1c-5ec9d738bd15.jpeg)

**Would you like to work on the issue?**

- [x] Yes
- [ ] No

**Comment by NitishGadangi** [comment]
@aggarwalpulkit596 bro, assign a bounty if eligible

**Comment by hardik-dua** [comment]
@NitishGadangi Can I start working on this issue?

**Comment by NitishGadangi** [comment]
@hardik0899 Sorry bro,
I already started working on it

**Comment by aggarwalpulkit596** [comment]
@NitishGadangi you cannot work on multiple issues at the same i would suggest take up one issue at a time

**Comment by adiig7** [comment]
Can I work on this issue @aggarwalpulkit596 ?

**Comment by NitishGadangi** [comment]
@aggarwalpulkit596 I have finished with the previous issue bro, so took up this issue
If eligible, Please assign a bounty bro

**Comment by adiig7** [comment]
@aggarwalpulkit596 sir no PR has been made till now, can I take up this issue?
