### ISSUE TITLE
Adding an option of copying the referral code beside the user's referral code

### ISSUE THREAD

**Issue by adiig7** [coding-blocks/CBOnlineApp#716]
**Describe the feature you'd like**

An image button can be added beside referral code which copies the referral code to clipboard when tapped.

**Screenshots**

![Screenshot (151)](https://user-images.githubusercontent.com/54351909/82048177-c70bec00-96d1-11ea-91f2-280f2e2287b7.png)
Just like this, we can change the background of the icon to transparent.

**Additional context**

Please review this and let me know if this is valid feature and can be added to the app.
Many apps having referral code feature have this option of copying to clipboard other than just share button.

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by adiig7** [comment]
@aggarwalpulkit596 please review this and let me know if we can add this feature or not.

**Comment by adarshraj365** [comment]
@aggarwalpulkit596  i would like to work on this .
can you help me out in finding kotlin file and xml file related to this issue

**Comment by aggarwalpulkit596** [comment]
Actually Aditya is already working on it so you can find another issue to
work on
