### ISSUE TITLE
Screen goes black on clicking Contents if there are no documents in Curriculum of a course

### ISSUE THREAD

**Issue by adiig7** [coding-blocks/CBOnlineApp#718]
**Describe the bug**

If there are 0 documents in a course curriculum and the contents button is clicked the screen colour changes to light gray, click it again, changes to dark grey and one or two more clicks it finally changes to black.

**To Reproduce**

1. Go to Dashboard
2. Click on **Continue Learning** if you are enrolled in any course.
3. Click on **Curriculum**.
4. Click on **Documents**.
5. Click on **Contents** if there are 0 documents in the course(for example *Kotlin for Beginners* 
    has 0 documents)
6. Click on **Contents** few more times

**Logs**

No logs

**Screenshots**

![Screenshot_20200515-180532_(Debug)Coding Blocks](https://user-images.githubusercontent.com/54351909/82051409-697a9e00-96d7-11ea-85e1-a08c6a61567b.jpg)

![Screenshot_20200515-180536_(Debug)Coding Blocks](https://user-images.githubusercontent.com/54351909/82051414-6a133480-96d7-11ea-9d54-f4b9986d5eda.jpg)

![Screenshot_20200515-180549_(Debug)Coding Blocks](https://user-images.githubusercontent.com/54351909/82051402-67184400-96d7-11ea-8ce2-16eeda3f7c10.jpg)
The screen hangs when the user clicks back button.

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Samsung Galaxy M30s|
|Android Version|Android 10.0|

**Additional context**

And if user clicks the back button of phone, the screen hangs, user need to reopen the app then.

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by adiig7** [comment]
@aggarwalpulkit596 sir what should be done this? I'm thinking of adding a textview saying **No documents in this course** and setting **Contents** visibility to false. Your reviews?

**Comment by aggarwalpulkit596** [comment]
So you can do one thing like make a empty textview with a button which will revert the state to default and the textview will work for any one of the type document code challenge and yes definitely hide the button but you need maintain all the cases feel free to ping me if you have issues.

**Comment by Dhruv-194** [comment]
Is someone working on this ? If not then please assign me this issue I will work on it

**Comment by vikashkmr519** [comment]
Can i work on this issue sir @aggarwalpulkit596

**Comment by aggarwalpulkit596** [comment]
Aditya is already working on this i guess

**Comment by Dhruv-194** [comment]
> Aditya is already working on this i guess

He hasn't made a PR yet....

**Comment by aggarwalpulkit596** [comment]
Then go ahead I'll merge whosever makes the PR first.

**Comment by adiig7** [comment]
@aggarwalpulkit596 It's been just 13 hours since I opened a issue,at least give me some time to work on it. I just can't make a PR in 2 hours.

**Comment by adiig7** [comment]
@Dhruv-194 @vikashkmr519 I'm working on this, i just can't make a PR in 2 or 3 hours.

**Comment by Dhruv-194** [comment]
> @Dhruv-194 @vikashkmr519 I'm working on this, i just can't make a PR in 2 or 3 hours.

Yes you go ahead with it.
 I'm not even getting this error. When I build the app on my phone it was working just fine there was no 'grey' and 'black' screen when I was clicking on the 'Contents' button. Neither did my phone hang and freeze.

**Comment by adiig7** [comment]
@Dhruv-194 yes sorry if you found my comment a bit rude, and its happening with me as you can see in the screenshots

**Comment by vikashkmr519** [comment]
@adiig7 Go ahead you can work on it.
