### ISSUE TITLE
Join Whatsapp Group section shows 'Install Whatsapp'

### ISSUE THREAD

**Issue by m-code12** [coding-blocks/CBOnlineApp#720]
**Describe the bug**
I wanted to join the whatsapp group for my course, but after clicking on it, it shows 'Please Install Whatsapp'. Even if the course group doesn't exist , we could redirect students to a group or a number where they could know about upcoming courses .

**To Reproduce**
1. Go to your purchased course
2. Click on continue learning.
3. Scroll down to Join Group
4. See error --> Please install whatsapp

**Expected behavior**
It should redirect to a whatsapp group .

**Screenshots**

![image](https://user-images.githubusercontent.com/53649201/82056480-a6e32980-96df-11ea-832d-22383981d1d4.png)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |[Oppo A3s]   |
|Android Version|[Oreo 8.1]    |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by Dhruv-194** [comment]
If this gets the 'bug bounty' tag then I will work on this issue. Please assign me this.

**Comment by aggarwalpulkit596** [comment]
@Dhruv-194 can you confirm this issue first because I'm not so sure about this one

**Comment by Dhruv-194** [comment]
> @Dhruv-194 can you confirm this issue first because I'm not so sure about this one

Yes I checked this issue it is correct. Even I also got the same error, I build the app on my phone where whatsapp is installed and still it showed the same error with that Toast Message. I am also attaching the screenshot of it from my phone.
Thank You for assigning me this. I will work on it.
![Screenshot_20200516-063619](https://user-images.githubusercontent.com/61137052/82106835-281ed880-9741-11ea-928e-ec54a10d15d4.png)

**Comment by m-code12** [comment]
@Dhruv-194 I have opened the issue and have also stated that I would like to work on it. So please look for another issue.

**Comment by m-code12** [comment]
@aggarwalpulkit596 Please assign me.

**Comment by aggarwalpulkit596** [comment]
@m-code12 @Dhruv-194 whosever fix the issue first will be given the bounty
 okay with both I guess ?

**Comment by m-code12** [comment]
@aggarwalpulkit596  What whatsapp number or group should I redirect the user to ??

**Comment by aggarwalpulkit596** [comment]
There should be url inside the function which handles this part

**Comment by Dhruv-194** [comment]
**### Suggested Edit to the issue**

The Bug 
The bug is actually that the 'WhatsApp group' card is getting displayed for the course which doesn't even have dedicated 'WhatsApp groups' and therefore giving that Toast Message of "Please Join WhatsApp".

Expected behavior
The 'WhatsApp Card' should not be shown for the courses which do not have the intended WhatsApp group that is card should not be displayed for the empty links.
