### ISSUE TITLE
Background should be transparent.

### ISSUE THREAD

**Issue by prince-09** [coding-blocks/CBOnlineApp#721]
**Describe the bug**
UI improvement- The bottom sheet's background should be transparent.

**To Reproduce**

1. Go to 'ALL Courses'
2. Click on 'Click on search box'
4. See on top corners it is not transparent and some padding around bottom sheet should be there.

**Expected behavior**
The background should be transparent.

**Screenshots**
![issue1](https://user-images.githubusercontent.com/52371330/82061116-ea409680-96e5-11ea-8037-a4ed8e82f79a.png)

**Smartphone Info:**

|Device         |Redmi 5a|
|Android Version|android 7.1    |

**Would you like to work on the issue?**
- [x] Yes
- [ ] No
- Other:

**Comment by Sujal123456** [comment]
Shall i solve this issue?

**Comment by Dhruv-194** [comment]
Please explain about the issue in detail. I am unable to understand what the issue is. The searchlayout is working perfectly. I am unable to understand what needs to be transparent?
