### ISSUE TITLE
Allow for Editing Profile picture via the Android app

### ISSUE THREAD

**Issue by jashasweejena** [coding-blocks/CBOnlineApp#724]
**Describe the feature you'd like**
The Android app can be used only to edit some fields of the profile, except for the Profile Picture.
I would like to work on a feature to set an avatar or upload a profile picture via the Android App like it is handled in the Web App.

**Screenshots**
![image](https://user-images.githubusercontent.com/20218197/82065248-81f4b380-96eb-11ea-8181-9dccbdbd3ff0.png)

This is a snap from the web version. I want to work on adding a similar kind of dialog in the Android App.

**Additional context**
I would like to add a button to the Edit Profile activity which allows the user to perform the above task.

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by jashasweejena** [comment]
@aggarwalpulkit596 Please, could you review this and let me know.

**Comment by aggarwalpulkit596** [comment]
There isn't api for that but if you can find out something it'll be great

**Comment by Sujal123456** [comment]
@aggarwalpulkit596 I'm willing to work on this issue

**Comment by jashasweejena** [comment]
> There isn't api for that but if you can find out something it'll be great
> 
> 

Okay. I will try to find something and then revert back to you

**Comment by prathamk22** [comment]
@Sujal123456 are you working on this or should I take this??
