### ISSUE TITLE
A popUp should be shown when clicked on any locked video.

### ISSUE THREAD

**Issue by prince-09** [coding-blocks/CBOnlineApp#725]
**Describe the feature you'd like**
A popUp should be shown when clicked on any locked video.

**Screenshots**
![issue3](https://user-images.githubusercontent.com/52371330/82068827-25e05e00-96f0-11ea-9af0-edc4bf6d22a6.png)

**Additional context**
For now, it is just closing the dropdown but there should be a dropdown.

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by Dhruv-194** [comment]
If this gets a 'bug bounty' tag then I would like to work on this issue. Please assign me this.

**Comment by aggarwalpulkit596** [comment]
There isn't any clickable action for these as it shows only the list of content nothing else
