### ISSUE TITLE
Bug: Content of couse still accessible after expiration of course

### ISSUE THREAD

**Issue by TanishqSanduja** [coding-blocks/CBOnlineApp#727]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/43672326/82069397-dfd7ca00-96f0-11ea-9c09-e92b9aaccebf.gif)
**Describe the bug**
Even after the expiration of course, the content of couse is still accessible. 

**To Reproduce**
1. From **Dashboard** go to **My Couses**.
2. Then go to **Expired Courses**.
3. Try to access content of the course through **Corriculum**.
4. The content of the course will be accessible.

**Expected behavior**
The content of the course should not be accessible.

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Redmi Note 4|
|Android Version| Nougat 7.0    |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by TanishqSanduja** [comment]
@aggarwalpulkit596 please review this and let me know if I can work on this issue.

**Comment by TanishqSanduja** [comment]
@aggarwalpulkit596 please reply as I want to take up this issue.

**Comment by aggarwalpulkit596** [comment]
Did you check whether the course was expired from website as well ? And the section was not free ?

**Comment by TanishqSanduja** [comment]
@aggarwalpulkit596 yes bhaiya the course was expired from website and it was not free and also I applied for the couse a year and a half before and did not buy any extension.
