### ISSUE TITLE
Bug : Referral code issue.

### ISSUE THREAD

**Issue by TanishqSanduja** [coding-blocks/CBOnlineApp#728]
**Describe the bug**
Every one has the same referal code and referral code is a link which on entering in google chrome leads to a whatsapp group joining link.

**To Reproduce**
1. Go to **Invite and Earn** Activity in **CBonlineApp**.
2. Use the **Referral Link** (Same for every one).
3. On using the link in **Google Chrome** would lead to a whatsapp group joining link.

**Expected behavior**

**Logs**

**Screenshots**
![WhatsApp Image 2020-05-15 at 9 44 48 PM](https://user-images.githubusercontent.com/43672326/82073547-07319580-96f7-11ea-92f7-966c5cd0ad98.jpeg)
![WhatsApp Image 2020-05-15 at 9 44 48 PM (1)](https://user-images.githubusercontent.com/43672326/82073509-f7b24c80-96f6-11ea-9800-967628dd87a6.jpeg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Redmi Note 4|
|Android Version|Nougat 7.0   |

**Additional context**
Also the whatsapp group cannot be joined as invite link is revoked.
 

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by TanishqSanduja** [comment]
@aggarwalpulkit596 please review this and let me know if I can work on this issue.

**Comment by TanishqSanduja** [comment]
@aggarwalpulkit596 please reply as I want to take up this issue.

**Comment by aggarwalpulkit596** [comment]
Duplicate

**Comment by nvmav** [comment]
@aggarwalpulkit596 This issue still exists in version 1.0.6 of app. 
Also, nothing happens when I click on share via whatsapp or More buttons
