### ISSUE TITLE
Bug: MORE button in Invite and Earn section is not working.

### ISSUE THREAD

**Issue by TanishqSanduja** [coding-blocks/CBOnlineApp#729]
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/43672326/82074731-d5b9c980-96f8-11ea-8fde-2b30d6f01057.gif)

**Describe the bug**
**More** button in **Invite and Earn** section of the **CBonlineApp** is not working or launching any activity.

**To Reproduce**
1. Go to **CBonlineApp**.
2. Go to **Invite and Earn** section.
3. Try tapping the **More** button.
4. It does not launch any new activity.

**Expected behavior**
It should launch any activity of the **CBonlineApp**.

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Redmi Note 4|
|Android Version|Nougat 7.0|

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by TanishqSanduja** [comment]
@aggarwalpulkit596 please review this and let me know if I can work on this issue.

**Comment by aggarwalpulkit596** [comment]
Duplicate
