### ISSUE TITLE
Leader Board ranking

### ISSUE THREAD

**Issue by gauthampkrishnan** [coding-blocks/CBOnlineApp#730]
Leader Board ranking is not getting displayed in mobile app. I am attaching the screenshot with this Issue.
![Screenshot_20200515-223907_Coding Blocks Online](https://user-images.githubusercontent.com/23455035/82077534-3c40e680-96fd-11ea-9db1-51afe48e0561.jpg)

**Comment by iamspathan** [comment]
@gauthampkrishnan  Are you working on this issue?

**Comment by Dhruv-194** [comment]
Yes I want to do this. 
@aggarwalpulkit596 kindly assign me this issue. I have certain progress as well now you can see that Leaderboard Layout is getting displayed, I am attaching the screenshot of it as well. The only problem is- Right now I am unable to find the code in the project which is displaying the 'Leaderboard' through the 'Coding Blocks Leaderboard API'. But I will do this.

![Screenshot_20200516-063644](https://user-images.githubusercontent.com/61137052/82106879-6e743780-9741-11ea-9f37-fb3e6cab38a9.png)

**Comment by gauthampkrishnan** [comment]
> @gauthampkrishnan Are you working on this issue?

Nope
