### ISSUE TITLE
View Profile and image icon should not be Present

### ISSUE THREAD

**Issue by SAMYAK99** [coding-blocks/CBOnlineApp#734]
**Describe the bug**
View Profile and image icon should not be Present 

**To Reproduce**

1. Just open the app
2. Click on Explore Courses
3. See error 

**Expected behavior**
View Profile and image icon should not be Present when User click on the Explore Courses . It is not good for user Experience and app  

**Logs**
D/skia: --- Failed to create image decoder with message 'unimplemented'
    --- Failed to create image decoder with message 'unimplemented'
D/skia: --- Failed to create image decoder with message 'unimplemented'
D/skia: --- Failed to create image decoder with message 'unimplemented'
D/skia: --- Failed to create image decoder with message 'unimplemented'
I/chatty: uid=10115(com.codingblocks.cbonlineapp.debug) glide-source-th identical 2 lines
D/skia: --- Failed to create image decoder with message 'unimplemented'
W/StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
W/FirebaseRemoteConfig: No value of type 'FirebaseRemoteConfigValue' exists for parameter key 'fpr_session_max_duration_min'.
W/FirebaseRemoteConfig: No value of type 'FirebaseRemoteConfigValue' exists for parameter key 'fpr_session_max_duration_min'.
D/skia: --- Failed to create image decoder with message 'unimplemented'
D/skia: --- Failed to create image decoder with message 'unimplemented'
D/skia: --- Failed to create image decoder with message 'unimplemented'
D/skia: --- Failed to create image decoder with message 'unimplemented'
D/skia: --- Failed to create image decoder with message 'unimplemented'
I/chatty: uid=10115(com.codingblocks.cbonlineapp.debug) glide-source-th identical 2 lines
D/skia: --- Failed to create image decoder with message 'unimplemented'
W/FirebaseRemoteConfig: No value of type 'FirebaseRemoteConfigValue' exists for parameter key 'fpr_session_max_duration_min'.
W/FirebaseRemoteConfig: No value of type 'FirebaseRemoteConfigValue' exists for parameter key 'fpr_session_max_duration_min'.
W/StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
W/StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
W/onlineapp.debu: Accessing hidden field Landroid/view/View;->mAccessibilityDelegate:Landroid/view/View$AccessibilityDelegate; (light greylist, reflection)
D/skia: --- Failed to create image decoder with message 'unimplemented'
D/skia: --- Failed to create image decoder with message 'unimplemented'
D/skia: --- Failed to create image decoder with message 'unimplemented'
D/skia: --- Failed to create image decoder with message 'unimplemented'
D/skia: --- Failed to create image decoder with message 'unimplemented'
I/chatty: uid=10115(com.codingblocks.cbonlineapp.debug) glide-disk-cach identical 2 lines
D/skia: --- Failed to create image decoder with message 'unimplemented'

**Screenshots**
![Screenshot_1589572317](https://user-images.githubusercontent.com/54956876/82091082-62be4c00-9714-11ea-912f-78f8bfc657fc.png)

**Smartphone Info:**
|Device         ||
|Android Version|    |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by SAMYAK99** [comment]
@aggarwalpulkit596  I want to work on this .

**Comment by Shubhamkakade06** [comment]
Can I work on this Issue?
