### ISSUE TITLE
Profile Image is missing

### ISSUE THREAD

**Issue by SAMYAK99** [coding-blocks/CBOnlineApp#735]
**Describe the bug**
User profile Image is missing in View Profile 

**To Reproduce**
1. Log in with your account
2. Click on Navigation Drawer
3. Click on View Profile

**Expected behavior**
Profile Image should be visible in view profile section

**Logs**
W/System.err: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT ÿØÿà��JFIF������...@1:49 in java.io.InputStreamReader@b3769fc) 
W/System.err:     at com.caverock.androidsvg.SVGParser.parseUsingXmlPullParser(SVGParser.java:761)
W/System.err:     at com.caverock.androidsvg.SVGParser.parse(SVGParser.java:603)
        at com.caverock.androidsvg.SVG.getFromInputStream(SVG.java:150)
W/System.err:     at com.codingblocks.cbonlineapp.util.extensions.ImageViewExtensionsKt$loadSvg$2.invoke(ImageViewExtensions.kt:29)
W/System.err:     at com.codingblocks.cbonlineapp.util.extensions.ImageViewExtensionsKt$loadSvg$2.invoke(Unknown Source:2)
        at org.jetbrains.anko.AsyncKt$doAsync$1.invoke(Async.kt:143)
        at org.jetbrains.anko.AsyncKt$doAsync$1.invoke(Unknown Source:0)
W/System.err:     at org.jetbrains.anko.AsyncKt$sam$java_util_concurrent_Callable$0.call(Unknown Source:2)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**Screenshots**
![Screenshot_1589573437](https://user-images.githubusercontent.com/54956876/82092676-5edff900-9717-11ea-9e80-0416bcc0b2af.png)
---Error---
![Screenshot_1589573448](https://user-images.githubusercontent.com/54956876/82092751-7c14c780-9717-11ea-8ca4-af08a501ab55.png)

**Smartphone Info:**
|Device         Redmi Note 7s|
|Android Version   [Pie 9]  |

**Comment by SAMYAK99** [comment]
@championswimmer  I am working on this.

**Comment by aggarwalpulkit596** [comment]
Duplicate
