### ISSUE TITLE
Add Dark Mode Support

### ISSUE THREAD

**Issue by iamspathan** [coding-blocks/CBOnlineApp#736]
**Describe the feature you'd like**

Users should be able to switch themes to dark mode. 

- [x] Yes
- [ ] No
- Other:

**Comment by iamspathan** [comment]
@aggarwalpulkit596 I'm taking this issue

**Comment by SAMYAK99** [comment]
@aggarwalpulkit596  I would love to work on this  😃

**Comment by aggarwalpulkit596** [comment]
@SAMYAK99 try to complete the first one then only I will be assigning you another task

**Comment by SAMYAK99** [comment]
Does this mean we can only work in one issue at a time 🙄

**Comment by aggarwalpulkit596** [comment]
@SAMYAK99 I would recommend to work on one make a PR then move to second one but first make a PR

**Comment by adiig7** [comment]
@aggarwalpulkit596  can i work on this?

**Comment by hardik-dua** [comment]
@iamspathan bro working on this??

**Comment by iamspathan** [comment]
Yes

**Comment by VibhorChinda** [comment]
@aggarwalpulkit596 can i take this issue ??

**Comment by aggarwalpulkit596** [comment]
Go ahead

**Comment by sunchit17** [comment]
Can I work on this ?

**Comment by prathamk22** [comment]
I am taking this up.
