### ISSUE TITLE
Hackerblocks Report 

### ISSUE THREAD

**Issue by SAMYAK99** [coding-blocks/CBOnlineApp#737]
**Describe the feature you'd like**
Hackerblocks ranking and report could be added just as in the courses section  in the Website . 

**Screenshots**
![a](https://user-images.githubusercontent.com/54956876/82094948-aff1ec00-971b-11ea-96b5-651499635bf7.jpeg)

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by iamspathan** [comment]
@aggarwalpulkit596 Can I work on this issue?

**Comment by SAMYAK99** [comment]
@aggarwalpulkit596  I am working on this  .

**Comment by aggarwalpulkit596** [comment]
@iamspathan @SAMYAK99 is working on this one

**Comment by aggarwalpulkit596** [comment]
@iamspathan I mean you can take up some other issue

**Comment by aggarwalpulkit596** [comment]
@iamspathan take this one
