### ISSUE TITLE
Buy Extension Issue

### ISSUE THREAD

**Issue by SAMYAK99** [coding-blocks/CBOnlineApp#738]
**Describe the bug**
I did not buy this Course so there is no need to buy the extension . Also Buy Extension Button is not working !!!!

**To Reproduce**
1. Try any courses for free
2. Click on locked Videos
3. See error -->

**Expected behavior**
Instead of buying the extension it should be better if it was written 'Buy the Complete Course' and Buy Course Buttton should be working . 

**Screenshots**
![b](https://user-images.githubusercontent.com/54956876/82095038-d9127c80-971b-11ea-95d5-414c1482a306.jpeg)

**Smartphone Info:**

|               | |
|---------------|-|
Device      -          Redmi Note 7s
Android Version   -   Pie 9

**Comment by SAMYAK99** [comment]
I am working on it to fix this error as soon as possible .

**Comment by shivamgohri** [comment]
I would love to work on this!

**Comment by aggarwalpulkit596** [comment]
@shivamgohri confirm with @SAMYAK99 that he haven't started this one

**Comment by SAMYAK99** [comment]
@aggarwalpulkit596  i had started working on it , will give the PR  as soon as possible 😅

**Comment by shivamgohri** [comment]
@SAMYAK99 Let me know! 
:)

**Comment by aggarwalpulkit596** [comment]
@SAMYAK99 you can't work on multiple issues at the same time

**Comment by SAMYAK99** [comment]
@aggarwalpulkit596  assign  me this one

**Comment by sachink-android** [comment]
I would like to work on this

**Comment by SAMYAK99** [comment]
Fixed !!!!
![typo](https://user-images.githubusercontent.com/54956876/82112282-09ccd300-9769-11ea-871f-669db911ccfe.png)

**Comment by gargVader** [comment]
Is this still open?

**Comment by YashKumarVerma** [comment]
100 bounty for a typo :scream:

**Comment by aggarwalpulkit596** [comment]
@YashKumarVerma this is not a typo

**Comment by YashKumarVerma** [comment]
> @YashKumarVerma this is not a typo

Apologies, but I think we must rename the PR to make it a bit more descriptive

**Comment by aggarwalpulkit596** [comment]
I'll change PR/issue title once the contributor confirm the exact issue as this is a logic issue not at all related to any spelling mistake
