### ISSUE TITLE
Bug : unable to search based on the 'text entered' on All Courses page

### ISSUE THREAD

**Issue by jayanttaparia** [coding-blocks/CBOnlineApp#739]
**Describe the bug**
Unable to get search results based on text entered on All Courses page.

**To Reproduce**
1. On App start up click 'Browse Courses' option at the boottom of the screen.
2. Click on 'View all courses' provided in the blue LinearLayout
3. Click on 'What do you want to learn ?'
4. See error: The pop comes up where we need to enter the course we want to learn. 
But there is no way se can get search result based on our text entered.

**Expected behavior**
On Entering the text we must have the option to click for search. 
But on clicking the search icon nothing happens.
Also the Keypad that opens up only takes us to newlines on pressing enter instead of instantiating a search.

**Screenshots**

![image](https://user-images.githubusercontent.com/37138009/82096144-08c28400-971e-11ea-984d-4b628738ba6c.png)

**Smartphone Info:**
|Device  :  RedmiNote 7S   ||
|Android Version  : Android Pie    |

**Would you like to work on the issue?**
- Other:

**Comment by aggarwalpulkit596** [comment]
Duplicate
