### ISSUE TITLE
Search view of All courses doesn't working OR not showing any list related

### ISSUE THREAD

**Issue by vikashkmr519** [coding-blocks/CBOnlineApp#741]
**What is the bug?**
The search view of the All Courses not working, as on searching it is not showing any item related to it.

**To Reproduce**

1. Go to 'Login page'
2. Click on 'Browse course'
3. Click on  'The Technology learning platform View All Courses '
4. Click on the above search view and try to search anything
5. See the error

**Expected behavior**
On searching anything in it, for eg Java, all the courses related to java should have been listed in it

**Screenshots**

![Screenshot_2020-05-16-02-28-02-737_com codingblocks cbonlineapp debug](https://user-images.githubusercontent.com/44942634/82097043-c00bca80-971f-11ea-8817-1edfaf324476.jpg)

![Screenshot_2020-05-16-02-27-07-676_com codingblocks cbonlineapp debug](https://user-images.githubusercontent.com/44942634/82097064-d023aa00-971f-11ea-8ccf-f6dce86ab21c.jpg)

![Screenshot_2020-05-16-02-27-28-409_com codingblocks cbonlineapp debug](https://user-images.githubusercontent.com/44942634/82097077-d6198b00-971f-11ea-9af3-405ec9a7cc37.jpg)

**Would you like to work on the issue?**

- ✔ Yes
- [ ] No

**Comment by vikashkmr519** [comment]
@aggarwalpulkit596  Sir if it is right to be worked upon, I would love to work on it. Please assign a suitable Bounty.

**Comment by iamspathan** [comment]
@vikashkmr519  This issue is already open on #722

**Comment by aggarwalpulkit596** [comment]
Duplicate
