### ISSUE TITLE
"Free trial courses" certificate section show bug

### ISSUE THREAD

**Issue by shivamgohri** [coding-blocks/CBOnlineApp#742]
**Describe the bug**
When we apply for "Try for free" course, course content shows bugged text for certificate generation in the course content! 

**To Reproduce**
1. Go to 'My Course'
2. Click on 'Course which is on free trial'
3. Scroll down to 'Generate Certificate'
4. See error -->

**Expected behavior**
A proper text should have been displayed.

**Screenshots**
![Screenshot_20200516-032853](https://user-images.githubusercontent.com/31760456/82099660-82aa3b80-9725-11ea-8564-fb523d1874f8.jpg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Oneplus 6|
|Android Version|Android 10   |

**Would you like to work on the issue?**

- [X] Yes
- [ ] No

**Comment by shivamgohri** [comment]
@aggarwalpulkit596 I would take this up!

**Comment by shivamgohri** [comment]
@aggarwalpulkit596 I need some initial guidance on this! I went deeper to Run, RunAttempt, and RunPerformance but couldn't figure out much! Thanks in advance :)

**Comment by aggarwalpulkit596** [comment]
@shivamgohri yeah tell me what do you want

**Comment by aggarwalpulkit596** [comment]
By the way all this information will be fetched from RunAttempt

**Comment by shivamgohri** [comment]
@aggarwalpulkit596  But the thing is 'viewModel.run' in OverviewFragment doesn't run for free trail courses, though I can see in logcat that all the information is being fetched!
So can I go ahead with something like this and display that you need to buy course to get certificate?

**Comment by aggarwalpulkit596** [comment]
@shivamgohri the thing you're referring to is the bug only which you need fix in the fist place so try to fix that one there just a minor issue if you're able to figure it out it would hardly take 2 lines of code

**Comment by shivamgohri** [comment]
@aggarwalpulkit596 I'm stuck! Hint, maybe?

**Comment by aggarwalpulkit596** [comment]
@shivamgohri what's the issue ?
