### ISSUE TITLE
Add editText to every Notes 

### ISSUE THREAD

**Issue by adarshraj365** [coding-blocks/CBOnlineApp#754]
**Inside Course->Library->Notes . it shows whole notes in a page .
we can add onClickListener to each note to read and edit the notes .
**
Implement onclickListener to each note and Implement functionality to edit and read notes in separate Activity ..

**Screenshots**

![Screenshot_2020-05-16-07-04-59-071_com codingblocks cbonlineapp](https://user-images.githubusercontent.com/44955367/82107471-9f566b80-9745-11ea-8b55-9094f18740c4.jpg)

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by adarshraj365** [comment]
@championswimmer Please review this Issue. I want to work on this issue.

**Comment by adarshraj365** [comment]
@aggarwalpulkit596  please review this issue .

**Comment by adarshraj365** [comment]
please assisgn this issue to me .
i would like to work on this issue .

**Comment by aggarwalpulkit596** [comment]
@adarshraj365 you can start working on this

**Comment by VibhorChinda** [comment]
@adarshraj365 are you still working on this issue ??

**Comment by shivamgohri** [comment]
@VibhorChinda I'm working on this!

**Comment by HaripriyaB** [comment]
@aggarwalpulkit596 can I take this coz there is no update from the author.

**Comment by aggarwalpulkit596** [comment]
Go ahead

**Comment by VibhorChinda** [comment]
@HaripriyaB are you still working on this ?? Can i take this issue ??

**Comment by HaripriyaB** [comment]
> 
> 
> @HaripriyaB are you still working on this ?? Can i take this issue ??

Yes I am. I'll be making a PR by tonight.

**Comment by HaripriyaB** [comment]
@VibhorChinda You go ahead with this.

**Comment by prathamk22** [comment]
I am taking this up
