### ISSUE TITLE
Invalid format of the credential during creating the account should validated before sending to the server.

### ISSUE THREAD

**Issue by Anirudhpolawar** [coding-blocks/CBOnlineApp#755]
**Describe the bug**
When we enter the wrong email format it is popping up the empty notifiers where it is expected that it should popup a notifier reporting the problem invalid email format. When entering the correct email format but the mobile number more than 10 digits it is redirecting to the new pager with the last 10 digits as the number.

**To Reproduce**
1 Go to create a new user
2 enter the invalid details

**Expected behavior**
It should mention which credentials are creating problems 

**Logs**
Empty notifier pops up.

**Screenshots**
![log](https://user-images.githubusercontent.com/36797874/82109035-d120ff80-9750-11ea-99dc-2d753bda1233.jpeg)
![log4](https://user-images.githubusercontent.com/36797874/82109282-47723180-9752-11ea-9e90-7ccd56a3c233.jpeg)
![log3](https://user-images.githubusercontent.com/36797874/82109029-cd8d7880-9750-11ea-9c21-7c5f31dcc1c8.jpeg)

**Smartphone Info:**
[Moto G5 Plus] 
[Oreo 8.1]     |

**Additional context**
Should write the validator at the device itself before sending to server

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by Anirudhpolawar** [comment]
@aggarwalpulkit596 please review this issue I want to work on this.

**Comment by aggarwalpulkit596** [comment]
Actually I'm already working  on the new login flow so don't create issues for that
