### ISSUE TITLE
Notifications Not Displayed

### ISSUE THREAD

**Issue by anshbajpai** [coding-blocks/CBOnlineApp#759]
**Describe the bug**
 Notification regarding courses is not being displayed under the notification page
 
![WhatsApp Image 2020-05-16 at 5 04 01 PM](https://user-images.githubusercontent.com/65030524/82113392-06e9d680-9799-11ea-9400-6757aa641af3.jpeg)

**To Reproduce**
1. Go to '.Coding Blocks App.'
2. Click on 'Notification Bell Icon'
3. See error -->

**Expected behavior**
 Should Show Notifications

**Smartphone Info:**

|               | |
|---------------|-|
|Device       | Oneplus 7 Pro |
|Android Version| Android 10     |

**Would you like to work on the issue?**
 
- [x] Yes
- [ ] No
- Other:

**Comment by RaghurajThombare** [comment]
Can i try to work on this?

**Comment by anshbajpai** [comment]
@RaghurajThombare i am doing it currently

**Comment by RaghurajThombare** [comment]
ok fine
