### ISSUE TITLE
Bugs/Improvements List

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/CBOnlineApp#76]
- [ ]  Show Quiz Result on quiz submission
- [ ] show marked/unmarked status in quiz bottom question sheet
- [x] bottom sheet gets dismissed completed on swiping down[Bug]
- [ ] show small rating bar in anko course card layout

**Comment by the-dagger** [comment]
> bottom sheet gets dismissed completed on swiping down[Bug]

Set the min peek height, us se ho jayega fix I think
