### ISSUE TITLE
All courses Certificate show same title

### ISSUE THREAD

**Issue by shivamgohri** [coding-blocks/CBOnlineApp#762]
**Describe the bug**
All course certificates show the same title "Complete 90% of the course to unlock certificate"
However, the Threshold Completion varies in the content of the certificate!

**To Reproduce**
1. Go to 'Any Course'
2. Scroll down to 'Generate Certificate'
3. Do this for many courses, you will see the error!

**Expected behavior**
Every certificate should be made personalized and should show the same text as content of the certificate.

**Screenshots**
![InkedScreenshot_20200516-183708_LI](https://user-images.githubusercontent.com/31760456/82120623-1bcc6700-97a5-11ea-9eb8-77935c85505f.jpg)
![InkedScreenshot_20200516-183716_LI](https://user-images.githubusercontent.com/31760456/82120637-2e46a080-97a5-11ea-8c52-b311654175dc.jpg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Oneplus 6|
|Android Version|Android 10|

**Additional context**

**Would you like to work on the issue?**

- [X] Yes
- [ ] No

**Comment by RaghurajThombare** [comment]
are you resolving it or may i try?@shivamgohri

**Comment by shivamgohri** [comment]
@RaghurajThombare  I'm already solving!
