### ISSUE TITLE
Not showing Login option in My purchase activity

### ISSUE THREAD

**Issue by vikashkmr519** [coding-blocks/CBOnlineApp#765]
**Describe the bug**

When we go to my purchases (if we are offline )then it is showing empty activity, I think it should give an option to login

**To Reproduce**

**Expected behavior**

It should show login option, to login in the app

**Screenshots**

![Screenshot_2020-05-16-03-30-20-747_com codingblocks cbonlineapp debug](https://user-images.githubusercontent.com/44942634/82123351-9baefd00-97b6-11ea-8afd-ab913b1c7d11.jpg)
'

**Would you like to work on the issue?**

- [ ✔ ] Yes
- [ ] No
- Other:

**Comment by vikashkmr519** [comment]
@aggarwalpulkit596 please assign bounty if work should be done on it.

**Comment by HaripriyaB** [comment]
There is no My Purchases page when not loggedin. So where does this issue exactly happen??

![Screenshot_2020-05-17-01-27-25-55_7a48d95313daa0d8bdbf7891041c354f](https://user-images.githubusercontent.com/34762451/82129096-f3149380-97dd-11ea-9bd4-baf40a9cabc5.png)

**Comment by aggarwalpulkit596** [comment]
Closing as this is not a relevant issue anymore
