### ISSUE TITLE
Non clickable Contacts in Contact Us

### ISSUE THREAD

**Issue by vikashkmr519** [coding-blocks/CBOnlineApp#766]
**Describe the bug**

In contact us , the below contacts and email id are non clickable 

**To Reproduce**

**Expected behavior**

All the contacts should directly make the call or email when clicked

**Screenshots**

![Screenshot_2020-05-16-03-29-06-562_com codingblocks cbonlineapp debug](https://user-images.githubusercontent.com/44942634/82123463-34457d00-97b7-11ea-925a-805081687df2.jpg)

**Would you like to work on the issue?**

- [  ✔] Yes
- [ ] No
- Other:

**Comment by vikashkmr519** [comment]
@aggarwalpulkit596 Please assign bounty if need to be worked on it, I want to work on it.

**Comment by hardik-dua** [comment]
> @aggarwalpulkit596 Please assign bounty if need to be worked on it, I want to work on it.

@vikashkmr519 this issue is already opened by @NitishGadangi 

See this https://github.com/coding-blocks/CBOnlineApp/issues/714

**Comment by aggarwalpulkit596** [comment]
Duplicate #714
