### ISSUE TITLE
Spelling mistake in DashBoard 

### ISSUE THREAD

**Issue by vikashkmr519** [coding-blocks/CBOnlineApp#767]
**Describe the bug**

Spelling mistake in dashboard when offline.

**To Reproduce**

**Expected behavior**

uour -> your

**Screenshots**

![Screenshot_2020-05-16-03-25-10-960_com codingblocks cbonlineapp debug](https://user-images.githubusercontent.com/44942634/82123679-4542be00-97b8-11ea-854f-aa50278e97d7.jpg)

**Would you like to work on the issue?**

- [  ✔] Yes
- [ ] No
- Other:

**Comment by vikashkmr519** [comment]
@aggarwalpulkit596 please assign the bounty if need to be worked upon. I would like to work on it, Although it is very easy.

**Comment by rahljoshi** [comment]
can you please assign me this

**Comment by pksgmv** [comment]
@aggarwalpulkit596 I have rectified the spelling mistake. Can you please check and respond if it's fine??
Thank You!!

**Comment by pksgmv** [comment]
@aggarwalpulkit596 It's added as a commit in the same PR as my last one from few hours ago. I am checking if I could make it as a separate PR...

**Comment by vikashkmr519** [comment]
https://github.com/coding-blocks/CBOnlineApp/pull/774
@aggarwalpulkit596 sir made the pull request for it please check it
