### ISSUE TITLE
After Adding notes the popup option will go away

### ISSUE THREAD

**Issue by RaghurajThombare** [coding-blocks/CBOnlineApp#772]
**Describe the feature you'd like**
After user will successfully store the Note then the popup option of " Add note" will be hide and the user can see the video

**Screenshots**

**Additional context**
Even if after the user stores the note the popup option is still visible and the video can be seen the user has to click on cross to make it go away.

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by Ankitchaudharyy** [comment]
I want to work to work on this issue @aggarwalpulkit596

**Comment by Ankitchaudharyy** [comment]
I want to work on this issue @aggarwalpulkit596

**Comment by RaghurajThombare** [comment]
i am working on it

**Comment by shivamgohri** [comment]
@RaghurajThombare The issue has been resolved and PR is also merged! Please close this issue! 
Thanks :)

**Comment by RaghurajThombare** [comment]
@shivamgohri so i was working on this issue and i am pursing MTech so our classes and assignments are happning online but still i manage to dedicate some time for the open source as this is my first time. I find issue by myself and what i thought is in a week i will complete the issue guess what some one just did a pull request on 4th day without informing me. So i decide to not do open source again in mylife thanks to you .
