### ISSUE TITLE
Onclicking Bookmark for a video nothing happens

### ISSUE THREAD

**Issue by RaghurajThombare** [coding-blocks/CBOnlineApp#773]
**Describe the bug**
For any course video after clicking on the bookmark nothing happens.

**To Reproduce**
1. Go to 'Any course Video'
2. Click on 'Bookmark icon'
3. Nothing happens 

**Expected behavior**
It should give toast that the bookmark is added the icon color will be changed and also it should be visible in the "my bookmarks" tab.

**Logs**

**Screenshots**

**Smartphone Info:**

|               | |
|---------------|-|
|Device         ||
|Android Version|    |

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by arsundram** [comment]
I am new to open source and would like to work on this issue. Can I take this?

**Comment by aggarwalpulkit596** [comment]
Duplicate #678
