### ISSUE TITLE
Sound/Volume control for course videos

### ISSUE THREAD

**Issue by RaghurajThombare** [coding-blocks/CBOnlineApp#778]
**Describe the feature you'd like**
There is no Separate sound control for the Videos, you have to use the mobile's volume buttons to increase or decrease the sound. If we put separate button on the video which can increase or decrease the sound it will be easier for the user.

**Screenshots**

![Screenshot (62)](https://user-images.githubusercontent.com/55155652/82135203-83be9400-981d-11ea-8b05-7b7969f4538c.png)

**Additional context**
It will be easy if the volume can be controlled only through the app. 

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by hardik-dua** [comment]
@RaghurajThombare are you working on it?

**Comment by RaghurajThombare** [comment]
yes

**Comment by adiig7** [comment]
@aggarwalpulkit596 can I work on it?

**Comment by aggarwalpulkit596** [comment]
Go ahead

**Comment by adiig7** [comment]
@aggarwalpulkit596 please assign bounty points to it.

**Comment by adiig7** [comment]
@RaghurajThombare why did you closed it? @aggarwalpulkit596 has already asked to solve this one and I have started working on it. @aggarwalpulkit596 please look into this.

**Comment by RaghurajThombare** [comment]
open it under your name

**Comment by RaghurajThombare** [comment]
This feature is just gimmick
