### ISSUE TITLE
'Vie..' should be replaced with 'View all' on main screen

### ISSUE THREAD

**Issue by pulkitmittal19** [coding-blocks/CBOnlineApp#779]
**Describe the feature you'd like**

In the app under **"Trending Now"** and **"learning tracks"** section. It should be **View all** or **View** instead of  **Vie** for better user understanding.

 
**Screenshots**

![issue_5](https://user-images.githubusercontent.com/53789333/82136785-bae97100-982e-11ea-9f97-b33547423aa4.jpg)

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by aggarwalpulkit596** [comment]
It's an issue for smaller screens it's already View All but with an ellipse but yeah can be done

**Comment by shivamgohri** [comment]
@pulkitmittal19 If you're not working on this, let me know, I'll do!

**Comment by pulkitmittal19** [comment]
> @pulkitmittal19 If you're not working on this, let me know, I'll do!
Yes!!
You can work on this.

**Comment by shivamgohri** [comment]
@pulkitmittal19 Which device was used while capturing this issue?

**Comment by shivamgohri** [comment]
@aggarwalpulkit596 (about this issue): Should I set ellipse property for "View All" TextView or for both "View All" TextView and TextView on its left, so that both sets themselves.
I can't see the output for smaller screens!

**Comment by aggarwalpulkit596** [comment]
i think for this we'll be needing a UI with smaller text sizes, less margin padding because ellipse is already set that's why it is showing as Vie... @shivamgohri
