### ISSUE TITLE
Improve padding of the Login with otp button

### ISSUE THREAD

**Issue by samjain2907** [coding-blocks/CBOnlineApp#780]
**Describe the bug**

The text in **Login with otp** button is not alligned properly. Its padding needs to be improved.

**Screenshots**

![WhatsApp Image 2020-05-17 at 13 20 18](https://user-images.githubusercontent.com/53353139/82138943-f93c5b80-9841-11ea-9099-570c48da4f28.jpeg)

**Would you like to work on the issue?**

- [ ] Yes
- [x] No
- Other:

**Comment by aggarwalpulkit596** [comment]
This is webview not android specific
