### ISSUE TITLE
Slider should be closed when we click outside of that slider

### ISSUE THREAD

**Issue by pulkitmittal19** [coding-blocks/CBOnlineApp#781]
**Describe the feature you'd like**

**Slider** should be **closed** when we click **outside** of that slider in the **login page**. But it only gets closed when we click on that more **menu option button**.

**Screenshots**

![issue_6](https://user-images.githubusercontent.com/53789333/82139132-6bfa0680-9843-11ea-9dcb-e2de7502e073.jpg)

**Would you like to work on the issue?**

- [ ] Yes
- [x] No
- Other:

**Comment by aggarwalpulkit596** [comment]
This is web view not android specific
