### ISSUE TITLE
"Retry button " message box should be resized when no error message is there

### ISSUE THREAD

**Issue by pulkitmittal19** [coding-blocks/CBOnlineApp#782]
**Describe the feature you'd like**

On the **create account** page, the **retry button** should be **resized** instead of 100% width when there is **no error message**.

**Screenshots**

![issue_7](https://user-images.githubusercontent.com/53789333/82139447-6a314280-9845-11ea-98dc-6b8a37831487.jpg)

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by aggarwalpulkit596** [comment]
@pulkitmittal19 i'm working on a new login flow so don't create anything related to this
