### ISSUE TITLE
app crashed while click on 'try it for free' button.

### ISSUE THREAD

**Issue by nitinvmit** [coding-blocks/CBOnlineApp#783]
Every time When I am trying to take 'Graph Algorithm' Course for trial and clicking on the 'try it for free' button , the app crashes. Here is the screenshot. Please Check it out & fix it. Thank You.

![photo_2020-05-17_15-24-56](https://user-images.githubusercontent.com/61305228/82141402-2fcea200-9853-11ea-8692-29c705563c54.jpg)

**Comment by shivamgohri** [comment]
Send the log details, it would be better to understand to cause of this issue! @nitinvmit
