### ISSUE TITLE
"Login with OTP" doesn't lets you login in the app

### ISSUE THREAD

**Issue by shivamgohri** [coding-blocks/CBOnlineApp#789]
**Describe the bug**
"Login with OTP" does not lets you log-in to the app, rather it just logs you in the app-browser but as soon as you press back, you are not logged-in and you have to log-in again!

**To Reproduce**
Firstly, log-out of the app.
1. Click on 'Login/Signup' -> click "Login with Google"
2. Type your 10-digit number in the number field
3. Click on "Login with OTP"
4. Enter the OTP you get, you are now logged-in
5. *Press back, now you're again at the log-in page*
(see the gif below)

**Expected behavior**
User should be logged-in as soon as the OTP gets confirmed and he/she should remain signed-in in the app like other log-in methods!

**Screenshots**
![loginotp_boss](https://user-images.githubusercontent.com/31760456/82156708-857a6d00-989a-11ea-8f88-b5ceca126aa2.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Oneplus 6|
|Android Version|Android 10   |

**Would you like to work on the issue?**

- [X] Yes
- [ ] No

**Comment by aggarwalpulkit596** [comment]
@abhishek97 @championswimmer  can we add re-direct for this as well?
