### ISSUE TITLE
No option to change password if user forgets the password

### ISSUE THREAD

**Issue by adiig7** [coding-blocks/CBOnlineApp#793]
**Describe the bug**

There isn't any option of **Forgot password** in  login page if user forgets the password.

**To Reproduce**

1. Open the app.
2. Click on **Mobile number or email id**
3. Click on **Use email**

**Expected behavior**

There should be an option to change password by an email link if user forgets the password of his account.

**Screenshots**

![Screenshot_20200518-075820_(Debug)Coding Blocks](https://user-images.githubusercontent.com/54351909/82169094-fee77f00-98dd-11ea-845d-12815dccabe3.jpg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Samsung Galaxy M30s|
|Android Version|Android 10.0|

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by adiig7** [comment]
@aggarwalpulkit596 please review this and add bounty points if its a valid issue. And I want to work on it.

**Comment by adiig7** [comment]
@aggarwalpulkit596 sir please let me know if its not a valid issue.

**Comment by aggarwalpulkit596** [comment]
Currently there isn't a api for this so let's keep this on hold
