### ISSUE TITLE
Add DownloadManager

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/CBOnlineApp#794]
Currently, there is no option to handle all the downloads which are currently in progress, queued or finished so we need a download manager for managing their states cancelling an individual maintaining their states etc

**Comment by aggarwalpulkit596** [comment]
You can take some help from here https://github.com/VdoCipher/sample-android-app

**Comment by jddeep** [comment]
@aggarwalpulkit596 Am taking this one.

**Comment by TanishqSanduja** [comment]
@aggarwalpulkit596 can third party libraries like PRDownloader can be used for this task.

**Comment by aggarwalpulkit596** [comment]
I don't think you'll be able to use any library but feel free to give it a try

**Comment by jddeep** [comment]
@aggarwalpulkit596 Herein we need to update the `DownloadService` class right?

**Comment by aggarwalpulkit596** [comment]
No it will be a seperate task

**Comment by jddeep** [comment]
@aggarwalpulkit596 Do you want this as a Service or as a class which can be extended and used in necessary activities?

**Comment by AkshobhyaP** [comment]
@aggarwalpulkit596 I would like to work on this issue. I plan on creating an activity from where we can manage all the downloads which can be accessed from a button in the action bar in the My Courses tab.
