### ISSUE TITLE
Add Promotion Banner

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/CBOnlineApp#796]
Add Promotion Banner as shown in Website to dashboard activity
<img width="1541" alt="Screenshot 2020-05-18 at 1 42 50 PM" src="https://user-images.githubusercontent.com/29139786/82189718-797bc300-990d-11ea-8fd7-ea3ee6b01964.png">

**Comment by HaripriyaB** [comment]
Can I work on it?

**Comment by aggarwalpulkit596** [comment]
@HaripriyaB sure

**Comment by HaripriyaB** [comment]
One doubt : should the banner be static ?

**Comment by aggarwalpulkit596** [comment]
All you need to inspect the website get the endpoint and add that endpoint to dashboard activity

**Comment by aggarwalpulkit596** [comment]
> One doubt : should the banner be static ?

static as in ?

**Comment by HaripriyaB** [comment]
okay got it clear.

**Comment by HaripriyaB** [comment]
The promotional banner is an image with url : https://images.codingblocks.com/img/live_web.jpg
So do I need to load this image like a banner on the dashboard or is there any other way ?

**Comment by aggarwalpulkit596** [comment]
Yes you have to load the image on dashboard

**Comment by aggarwalpulkit596** [comment]
There will be a mobile-specific banner in the API response so you need to use that once it's implemented on backend

**Comment by HaripriyaB** [comment]
Oh! I was about to make a PR. 
![Screenshot_2020-05-18-21-05-38-90_7a48d95313daa0d8bdbf7891041c354f](https://user-images.githubusercontent.com/34762451/82231957-8ddeb080-994b-11ea-8b39-9c2dd2d2f48b.png)

Okay I'll wait 👍 Pls do ping me when it's done.

**Comment by thefaisalkhan** [comment]
@aggarwalpulkit596  can you explain little bit more

**Comment by aggarwalpulkit596** [comment]
@HaripriyaB you can implement this now there's a mobile banner image in the response

**Comment by HaripriyaB** [comment]
sure...from where can I get the mobile banner image?

**Comment by aggarwalpulkit596** [comment]
Using the same api there is a new json element for mobile now

**Comment by HaripriyaB** [comment]
not sure how to fetch json element for mobile banner image...

**Comment by HaripriyaB** [comment]
@aggarwalpulkit596 bhaiya I can't find the json element in OnlineJsonAPI and OnlineRestAPI files. Can you pls tell me where exactly it is?

**Comment by aggarwalpulkit596** [comment]
Did you check the api for getting banner image ?

**Comment by HaripriyaB** [comment]
no.....

**Comment by prathamk22** [comment]
I'm taking this up.

**Comment by prathamk22** [comment]
Working on it.
