### ISSUE TITLE
Add Leaderboard in Overview Fragment

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/CBOnlineApp#797]
Add the leaderboard list in the course.
It will an optional section as all courses do not have leaderboards.
Design references are attached below
<img width="464" alt="Screenshot 2020-05-18 at 1 49 31 PM" src="https://user-images.githubusercontent.com/29139786/82190255-687f8180-990e-11ea-9c6a-4b5a8e019284.png">

**Comment by jddeep** [comment]
@aggarwalpulkit596 Will work on this

**Comment by jddeep** [comment]
Can you please help me out with the reason of build failures #785 , #791 .

**Comment by aggarwalpulkit596** [comment]
Rebasing your PR should do the trick

**Comment by aggarwalpulkit596** [comment]
@jddeep I've deducted 100 points here because there were certain issues in your implementation.

**Comment by jddeep** [comment]
@aggarwalpulkit596 No issues. Got to learn :)
