### ISSUE TITLE
Auto Delete Expired Downloads

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/CBOnlineApp#798]
Write a Worker Request which will delete the expired downloads usually they have a life of 15 days
So after 15 days, a video should be deleted automatically.

**Comment by jddeep** [comment]
@aggarwalpulkit596 Any heads-up about how to approach for this?

**Comment by aggarwalpulkit596** [comment]
I have already given that make a worker request for this

**Comment by HaripriyaB** [comment]
I have an approach. To use ScheduledExecutorService and Executors. But I'm not sure will it work on all the downloaded files. So I can work on it. But If someone else issue a PR I don't have any problem. It's all in the learning :-)

**Comment by aggarwalpulkit596** [comment]
Yes you can try that or just writing onetime worker request would do the job 😅

**Comment by HaripriyaB** [comment]
The worker request is fine. But how to keep track of the files time for 15days. That's what is confusing. And each file might have different time of download so, how to go about the times.

**Comment by aggarwalpulkit596** [comment]
Whenever a particular download is completed just make  worker request that will be executed after 15 days

**Comment by aggarwalpulkit596** [comment]
if you want to make it more efficient you can do one thing to make only one WorkerRequest for a single day by keeping the date as a tag that way only worker request will be executed for one day of downloads

**Comment by prathamk22** [comment]
@aggarwalpulkit596 @HaripriyaB are you working on this or should I take this up?

**Comment by HaripriyaB** [comment]
> 
> 
> @aggarwalpulkit596 @HaripriyaB are you working on this or should I take this up?

I haven't taken this up. So u can go ahead.

**Comment by prathamk22** [comment]
Cool then, I am taking this up.
