### ISSUE TITLE
Add announcements in Library

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/CBOnlineApp#799]
Add support for announcements in course library
They should be saved into the database as well

**Comment by prince-09** [comment]
Can I take this?

**Comment by aggarwalpulkit596** [comment]
@prince-09 sure go ahead

**Comment by aggarwalpulkit596** [comment]
You can take reference of #790 for how things should be laid out

**Comment by lfsabcd7** [comment]
@prince-09  are you still working on this issue?

**Comment by prince-09** [comment]
NO you can take it

**Comment by jddeep** [comment]
I will be taking this up

**Comment by jddeep** [comment]
@aggarwalpulkit596 Is an API interacting method with necessary path for fetching announcements already implemented here? If not this is what I came across https://online-api.codingblocks.com/api/v2/announcements. Let me know your thoughts on this

**Comment by aggarwalpulkit596** [comment]
Announcements will be specific to course only and there isn't any method
integrated as of now in the app
