### ISSUE TITLE
Progress bar doesn't shows realtime values in CB android Application.

### ISSUE THREAD

**Issue by KmrAnish04** [coding-blocks/CBOnlineApp#803]
**Describe the bug**
In Coding Blocks android application, the progress bar doesn't shows real time progress values after watching some videos lectures. It doesn't get updated after watching some video lectures. The progress bar only gets updated when we restart the application or click on "Continue Learning" button.

**To Reproduce**
<!--Steps to reproduce the behavior:
1. Open the coding blocks android application and note your course progress percentage value of any of your course.
2. Now watch some video lectures of your any course(don't repeat the previous watched lectures, watch a new one to increase your growth on course progress bar in dashboard.)
3. Now you will observe that your course progress  bar is showing old values and is not get updated after watching video lectures in dashboard.
4. (1) Now close your application and restart the application, now you will observe that your progress bar gets updated on your dashboard.

**Expected behavior**
The course progress bar must have to show the realtime progress values in the application after watching any video lectures without restarting the application. 

**Screenshots**
Progress bar is at 53%.

![Screenshot_2020-05-18-14-34-15-43_8145aea08c2fe477f98d57a512aa848b](https://user-images.githubusercontent.com/58399776/82223501-5ddde000-9940-11ea-9541-3291c82849e7.jpg)

After watching a video lecture and restarting the application.
Progress bar is at is 55%.

![Screenshot_2020-05-18-14-53-54-00](https://user-images.githubusercontent.com/58399776/82223691-9aa9d700-9940-11ea-8bb8-38e720eefa8a.jpg)

**Smartphone Info:**

Device Realme 5 pro        
Android Version  e.g.  Android version 10

**Would you like to work on the issue?**
- Other:

**Comment by Anish1903** [comment]
In Coding Blocks android application, the progress bar doesn't shows real time progress values after watching some videos lectures. It doesn't get updated after watching some video lectures. The progress bar only gets updated when we restart the application or click on "Continue Learning" button.

Screenshots:

Progress bar is at 53%.

Screenshot_2020-05-18-14-34-15-43_8145aea08c2fe477f98d57a512aa848b

After watching a video lecture and restarting the application.
Progress bar is at is 55%.

Screenshot_2020-05-18-14-53-54-00
