### ISSUE TITLE
Not able to complete payment for course

### ISSUE THREAD

**Issue by nvmav** [coding-blocks/CBOnlineApp#846]
**Describe the bug**

**To Reproduce**
1. Go to any course page
2. Click on choose batch at top right
3. Select batch and click proceed to buy
4. Click next at bottom right
5. choose state and click next
6. click on proceed to pay

Now razorpay loading icon is shown and app crashes. After sometime, it shows home page 

**Expected behavior**
App must go to payment gateway and allow us to pay for the course in the cart

**Logs**

**Screenshots**

![ss1](https://user-images.githubusercontent.com/6573890/82955323-3506bc00-9fcc-11ea-9f61-33b1f5b47865.png)
![ss2](https://user-images.githubusercontent.com/6573890/82955324-3637e900-9fcc-11ea-8923-3d7fecd21121.png)

**Smartphone Info:**

|               |
|--------------
|Device: ASUS_X01BDA|
|Android Version:  9|
|App version: 1.0.5|

**Additional context**

**Would you like to work on the issue?**

- [ ] Yes
- [x] No
- Other:

**Comment by aggarwalpulkit596** [comment]
This has been fixed but hasn't been deployed as of now.
