### ISSUE TITLE
Add app demo using Spotlight

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/CBOnlineApp#854]
References
https://github.com/TakuSemba/Spotlight

**Comment by prathamk22** [comment]
Taking up this one.

**Comment by vibhuti019** [comment]
I will work on it

**Comment by prathamk22** [comment]
@vibhuti019 I started working on it already. Pls take some other bug

**Comment by hardik-dua** [comment]
@prathamk22 bro are you working on this ?

**Comment by prathamk22** [comment]
Nope. You can take this up

**Comment by hardik-dua** [comment]
> Nope. You can take this up

Ok Let me try this one

**Comment by abishekvashok** [comment]
Can I work on it pls?

**Comment by aggarwalpulkit596** [comment]
Go ahead

**Comment by AkshobhyaP** [comment]
@aggarwalpulkit596 can I take up this issue.

**Comment by rhythm98** [comment]
Can I work on this issue? @aggarwalpulkit596
