### ISSUE TITLE
Add support to save downloads in SD Card

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/CBOnlineApp#866]
Add a preference option in setting to save downloads in memory card(only if there's one)

**Comment by mohitpanwar09** [comment]
i am solving this @aggarwalpulkit596

**Comment by abishekvashok** [comment]
Hey @mohitpanwar09 @aggarwalpulkit596 can I work on it pls?

**Comment by mohitpanwar09** [comment]
@abishekvashok yes bro you can

**Comment by rhythm98** [comment]
Can I work on this issue?
