### ISSUE TITLE
Feature request: prev and next button in the video player.

### ISSUE THREAD

**Issue by pradeexsu** [coding-blocks/CBOnlineApp#884]
# Description of Feature :previous_track_button: and :next_track_button:
   - play prev :previous_track_button: for all video except first video of the course and
   - play next :next_track_button: button for all video except last video in the video player.
<hr>

**Current Screenshots**
<img src="https://i.ibb.co/VSqjBNB/imge.png" height=200>

**Comment by pradeexsu** [comment]
@aggarwalpulkit596 bhaiya, please review this issue.

**Comment by Codedude1** [comment]
@boss-contributions-bot claim

**Comment by abishekvashok** [comment]
@sutharp777 @aggarwalpulkit596 can I work on it?

**Comment by pradeexsu** [comment]
### welcome @abishekvashok .

**Comment by prathamk22** [comment]
Working on this
