### ISSUE TITLE
Feature request: Auto Play Next mode in the video player.

### ISSUE THREAD

**Issue by pradeexsu** [coding-blocks/CBOnlineApp#885]
## Description of the feature :play_or_pause_button: 
  - Autoplay next mode in the video player.
  - User can enable or disable this mode.
  - This mode should work on all the videos except the last video of the course.

## additional feature (Optional) :desktop_computer: 
 - we can program this, such that it should play the next unmarked video in the autoplay option.

## benefits of the feature :rocket: 
 - no need to go back to course contains and play the next video.

**Comment by pradeexsu** [comment]
@aggarwalpulkit596 bhaiya review this.

**Comment by Coolcodings888** [comment]
Can i work on this issue?

**Comment by aggarwalpulkit596** [comment]
Go ahead
