### ISSUE TITLE
Bug Report : MCQ with long option not visible completely.

### ISSUE THREAD

**Issue by pradeexsu** [coding-blocks/CBOnlineApp#888]
**Description of the bug:beetle: :** 
if option statement is long than last option is not visible completely.

**To Reproduce** 
1. Go to CB-App
2. Attempt any Quiz who's option are large enough.
3. Scroll down to
4. See the last option's last line not visible completely.

**Expected behavior** 
 - at least last option should completely visible.

**Screenshots** :scroll: 
<img src="https://i.ibb.co/cLwB9S4/src.gif" height=500>

**Smartphone Info: :iphone:**
|Description| |
|------------------|-|
| Device Name   | Vivo Y12 |
| Android Version| 9  |
| Android | Android P|
| Screen Resolution | 720x1544 pixels|
| Aspect ratio | 19.3:9 |

**Additional context**
 - either full screen for quiz time.
 - change font size such that all option are fit in available screen.

**Comment by pradeexsu** [comment]
@aggarwalpulkit596 bhaiya, please review this issue, if it is relevant.

**Comment by adiig7** [comment]
Can I work on this?

**Comment by Coolcodings888** [comment]
I want to work on this issue.

**Comment by pradeexsu** [comment]
welcome, if any one wants to work on this one.
