### ISSUE TITLE
Feature Request : Auto-Hide Controls in Video Player.

### ISSUE THREAD

**Issue by pradeexsu** [coding-blocks/CBOnlineApp#892]
### Description of Feature :play_or_pause_button:
 - if the user is not using controls from the last few seconds, it means there is no need for video controls as of now.
 - and it makes sense that it should auto-hide if it is not in use (from last 4-5 seconds).
 - if we tap anywhere on-screen, it should show back the same. and again auto-hide after few seconds if not in use.

### Current Feature :pager:
  - we have to tap anywhere else on the screen to hide the controls.
 - and toggle the same by tap again.

### Screenshots :iphone: 
 ![](https://i.ibb.co/tDFQR74/autohid.png)

### Additional context :gear: 
 - we can add enable or disable this option from setting in video controls.

**Would you like to work on the issue?**

- [x] Yes
- [ ] No

**Comment by pradeexsu** [comment]
@aggarwalpulkit596 bhaiya, please review this issue.

**Comment by aggarwalpulkit596** [comment]
This is not relevant as there is timeout which does hide the controls automatically

**Comment by pradeexsu** [comment]
@aggarwalpulkit596 bhaiya this feature is about very short intervel of time around 2 to 3 or 4 seconds , where as timeout feature is long intervel of time. And Time out is rear event.
I am talking about the feature like YouTube.
If we skip 10 second, than the control is auto hide after skipping.

**Comment by pradeexsu** [comment]
> @aggarwalpulkit596 bhaiya this feature is about very short intervel of time around 2 to 3 or 4 seconds , where as timeout feature is long intervel of time. And Time out is rear event.
> I am talking about the feature like YouTube.
> If we skip 10 second, than the control is auto hide after skipping.
@aggarwalpulkit596 bhaiya please review this

**Comment by aggarwalpulkit596** [comment]
You can start working on this

**Comment by sutharp777** [comment]
Goal of this feature is make as follow :
![image loading might take long as it is of 5MB](https://i.ibb.co/j3Sgq93/youtube.gif)

**Comment by pradeexsu** [comment]
@aggarwalpulkit596  bhaiya assign label to this, i am working on some other issue, if some one want's to work, than they can.

**Comment by pradeexsu** [comment]
@aggarwalpulkit596 :pray:  please add lable to this.
