### ISSUE TITLE
Cache SVG for offline loading of course log/poster images

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/CBOnlineApp#90]

**Comment by aggarwalpulkit596** [comment]
https://developer.android.com/topic/performance/graphics/cache-bitmap @championswimmer should i try this method

**Comment by championswimmer** [comment]
Via memory cache using LRU ? That sounds like a good method.

**Comment by championswimmer** [comment]
I think we should use a Disk cache rather

**Comment by aggarwalpulkit596** [comment]
Closed vi #101
