### ISSUE TITLE
Feature request : Touch Lock Option while video playing. 

### ISSUE THREAD

**Issue by pradeexsu** [coding-blocks/CBOnlineApp#919]
## Touch Lock  Option while video playing :lock:  
 - when we enable this option, touch will not work on screen other than lock icon in screen. 
 - touch anywhere on screen toggle the icon visibility.

## Screenshots
 ![](https://www.androidpolice.com/wp-content/uploads/2020/04/netflix-screen-lock-1-668x376.jpg)
 ![](https://www.androidpolice.com/wp-content/uploads/2020/04/netflix-screen-lock-2-668x376.jpg)
 ![](https://www.androidpolice.com/wp-content/uploads/2020/04/netflix-screen-lock-3-668x376.jpg)

## Additional context
 - the actual placement of icon may not be in center like in these photos they are just for reference.

 ## Need of this feature
 - it reduces the accidental touch on screen while playing video.

**Comment by pradeexsu** [comment]
@aggarwalpulkit596 bhaiya  review this.

**Comment by prathamk22** [comment]
Working on it.
