### ISSUE TITLE
ViewPager bottom dots are not updating

### ISSUE THREAD

**Issue by prudhvir3ddy** [coding-blocks/CBOnlineApp#944]
**Describe the bug**

when scrolling through the view pager the dots are not updating, please find the video in below link 
https://streamable.com/z2syme

**To Reproduce**
1. run the app 
2. on first screen you can see the viewpager
3. try scrolling it and you can see dots are not updating

**Expected behavior**
1. dots should give scrolling behaviour to update to next dot

**Screenshots**

https://streamable.com/z2syme

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | One plus 3 |
|Android Version| nougat 9 |

**Would you like to work on the issue?**

- [X] Yes
- [ ] No
- Other:

**Comment by prudhvir3ddy** [comment]
@aggarwalpulkit596 just want to understand should we have an auto-scrolling behaviour on this page?

because right now it's not automatically scrolling but in code i am seeing duration and all

**Comment by prudhvir3ddy** [comment]
also, right now it's using viewpager should I remove it and add viewpager2 there ? because util function is created for viewpager2 

or should i create util function for normal viewpager and make it a easy fix ?

**Comment by aggarwalpulkit596** [comment]
Yes I think you should use viewpager2 with this one as well
