### ISSUE TITLE
Add infinite scrolling in the intro screen. 

### ISSUE THREAD

**Issue by prudhvir3ddy** [coding-blocks/CBOnlineApp#947]
**Describe the feature you'd like**
currently, the intro screen viewpager's infinite scrolling is not working, I moved the code to viewpager2 in this PR by fixing the dots issue in this PR #946 . 

this issue is to create infinite scrolling in the migrated code

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by aggarwalpulkit596** [comment]
Are you still doing this ?

**Comment by prudhvir3ddy** [comment]
> Are you still doing this ?

Yes. I will send PR by tomorrow

**Comment by prudhvir3ddy** [comment]
was little I will find some free time in next two days
